<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-07-03">
<meta name="description" content="Keretérték-alapú előszezoni pontszám-előrejelzés az NB1-ben: adatforrások, korlátok, modell.">

<title>Levente Kaszai - NB1 előszezoni tabella-modell — Módszertani dokumentáció</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&amp;display=swap" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Levente Kaszai</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archivum.html" rel="" target="">
 <span class="menu-text">Archívum</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-kosárlabda" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Kosárlabda</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-kosárlabda">    
        <li>
    <a class="dropdown-item" href="../kosarlabda/four_factors_1.html" rel="" target="">
 <span class="dropdown-text">Four Factors</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../kosarlabda/scoring_efficiency.html" rel="" target="">
 <span class="dropdown-text">Scoring Efficiency</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../kosarlabda/pace_efficiency.html" rel="" target="">
 <span class="dropdown-text">Játékritmus &amp; Hatékonyság</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../kosarlabda/analytics.html" rel="" target="">
 <span class="dropdown-text">🔒 Analytics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../kosarlabda/player_ratings.html" rel="" target="">
 <span class="dropdown-text">Játékosértékelés</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../kosarlabda/jatekosok.html" rel="" target="">
 <span class="dropdown-text">Játékos profilok</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labdarúgás" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Labdarúgás</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labdarúgás">    
        <li>
    <a class="dropdown-item" href="../futball/nb1_power_ranking.html" rel="" target="">
 <span class="dropdown-text">NB1 Power Ranking</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../futball/nb1_elorejelzesek.html" rel="" target="">
 <span class="dropdown-text">🔒 Előrejelzések</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../futball/analytics.html" rel="" target="">
 <span class="dropdown-text">🔒 Analytics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../futball/team_analytics.html" rel="" target="">
 <span class="dropdown-text">🔒 Team Analytics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../futball/player_ratings.html" rel="" target="">
 <span class="dropdown-text">Játékosértékelés</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../futball/jatekosok.html" rel="" target="">
 <span class="dropdown-text">Játékos profilok</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/leventekaszai" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tartalom</h2>
   
  <ul>
  <li><a href="#cél" id="toc-cél" class="nav-link active" data-scroll-target="#cél">Cél</a></li>
  <li><a href="#miért-a-keretérték" id="toc-miért-a-keretérték" class="nav-link" data-scroll-target="#miért-a-keretérték">Miért a keretérték?</a></li>
  <li><a href="#adatforrások" id="toc-adatforrások" class="nav-link" data-scroll-target="#adatforrások">Adatforrások</a>
  <ul class="collapse">
  <li><a href="#keretérték-transfermarkt" id="toc-keretérték-transfermarkt" class="nav-link" data-scroll-target="#keretérték-transfermarkt">1. Keretérték — Transfermarkt</a></li>
  <li><a href="#végeredmény-pontszám" id="toc-végeredmény-pontszám" class="nav-link" data-scroll-target="#végeredmény-pontszám">2. Végeredmény (pontszám)</a></li>
  <li><a href="#csapatnév-egyeztetés" id="toc-csapatnév-egyeztetés" class="nav-link" data-scroll-target="#csapatnév-egyeztetés">3. Csapatnév-egyeztetés</a></li>
  </ul></li>
  <li><a href="#az-egyesített-adatkészlet" id="toc-az-egyesített-adatkészlet" class="nav-link" data-scroll-target="#az-egyesített-adatkészlet">Az egyesített adatkészlet</a></li>
  <li><a href="#modell" id="toc-modell" class="nav-link" data-scroll-target="#modell">Modell</a>
  <ul class="collapse">
  <li><a href="#alapmodell" id="toc-alapmodell" class="nav-link" data-scroll-target="#alapmodell">Alapmodell</a></li>
  <li><a href="#feljutó-csapat-dummy" id="toc-feljutó-csapat-dummy" class="nav-link" data-scroll-target="#feljutó-csapat-dummy">Feljutó csapat dummy</a></li>
  <li><a href="#validáció-walk-forward-expanding-window-nem-leave-one-season-out" id="toc-validáció-walk-forward-expanding-window-nem-leave-one-season-out" class="nav-link" data-scroll-target="#validáció-walk-forward-expanding-window-nem-leave-one-season-out">Validáció — walk-forward (expanding window), nem leave-one-season-out</a></li>
  </ul></li>
  <li><a href="#kiegészítő-prediktorok-szisztematikus-átvizsgálás" id="toc-kiegészítő-prediktorok-szisztematikus-átvizsgálás" class="nav-link" data-scroll-target="#kiegészítő-prediktorok-szisztematikus-átvizsgálás">Kiegészítő prediktorok — szisztematikus átvizsgálás</a>
  <ul class="collapse">
  <li><a href="#előző-szezoni-forma-mutatók-lag-és-a-többszörös-összehasonlítás-csapdája" id="toc-előző-szezoni-forma-mutatók-lag-és-a-többszörös-összehasonlítás-csapdája" class="nav-link" data-scroll-target="#előző-szezoni-forma-mutatók-lag-és-a-többszörös-összehasonlítás-csapdája">Előző szezoni forma-mutatók (lag), és a többszörös összehasonlítás csapdája</a></li>
  <li><a href="#pénzügyi-mutatók-bevétel-és-személyi-jellegű-ráfordítás" id="toc-pénzügyi-mutatók-bevétel-és-személyi-jellegű-ráfordítás" class="nav-link" data-scroll-target="#pénzügyi-mutatók-bevétel-és-személyi-jellegű-ráfordítás">Pénzügyi mutatók: bevétel és személyi jellegű ráfordítás</a></li>
  <li><a href="#miért-nincs-még-többváltozós-modell" id="toc-miért-nincs-még-többváltozós-modell" class="nav-link" data-scroll-target="#miért-nincs-még-többváltozós-modell">Miért nincs (még) többváltozós modell</a></li>
  </ul></li>
  <li><a href="#végleges-modell-és-2026-27-előrejelzés" id="toc-végleges-modell-és-2026-27-előrejelzés" class="nav-link" data-scroll-target="#végleges-modell-és-2026-27-előrejelzés">Végleges modell és 2026-27 előrejelzés</a>
  <ul class="collapse">
  <li><a href="#miért-nem-a-naiv-többmodell-átlag-és-miért-nem-külön-feljutó-modell" id="toc-miért-nem-a-naiv-többmodell-átlag-és-miért-nem-külön-feljutó-modell" class="nav-link" data-scroll-target="#miért-nem-a-naiv-többmodell-átlag-és-miért-nem-külön-feljutó-modell">Miért nem a naiv többmodell-átlag, és miért nem külön feljutó-modell</a></li>
  <li><a href="#a-feljutók-keretérték-modell-nb2-mint-leíró-kontextus" id="toc-a-feljutók-keretérték-modell-nb2-mint-leíró-kontextus" class="nav-link" data-scroll-target="#a-feljutók-keretérték-modell-nb2-mint-leíró-kontextus">A feljutók: keretérték-modell + NB2 mint leíró kontextus</a></li>
  <li><a href="#végleges-egyesített-2026-27-tábla" id="toc-végleges-egyesített-2026-27-tábla" class="nav-link" data-scroll-target="#végleges-egyesített-2026-27-tábla">Végleges egyesített 2026-27 tábla</a></li>
  </ul></li>
  <li><a href="#gólmodell-a-poisson-szimulációhoz" id="toc-gólmodell-a-poisson-szimulációhoz" class="nav-link" data-scroll-target="#gólmodell-a-poisson-szimulációhoz">Gólmodell a Poisson-szimulációhoz</a>
  <ul class="collapse">
  <li><a href="#screening-mi-jósolja-legjobban-a-következő-szezon-lőttkapott-gólját" id="toc-screening-mi-jósolja-legjobban-a-következő-szezon-lőttkapott-gólját" class="nav-link" data-scroll-target="#screening-mi-jósolja-legjobban-a-következő-szezon-lőttkapott-gólját">Screening: mi jósolja legjobban a következő szezon lőtt/kapott gólját</a></li>
  <li><a href="#walk-forward-validáció-és-a-végleges-választás" id="toc-walk-forward-validáció-és-a-végleges-választás" class="nav-link" data-scroll-target="#walk-forward-validáció-és-a-végleges-választás">Walk-forward validáció és a végleges választás</a></li>
  <li><a href="#várható-lőttkapott-gól-csapatonként" id="toc-várható-lőttkapott-gól-csapatonként" class="nav-link" data-scroll-target="#várható-lőttkapott-gól-csapatonként">2026-27 várható lőtt/kapott gól csapatonként</a></li>
  <li><a href="#attackdefense-rating-és-a-mérkőzés-szintű-lambda" id="toc-attackdefense-rating-és-a-mérkőzés-szintű-lambda" class="nav-link" data-scroll-target="#attackdefense-rating-és-a-mérkőzés-szintű-lambda">Attack/defense rating és a mérkőzés-szintű lambda</a></li>
  <li><a href="#dixon-coles-alacsony-gólszámú-korrekció-saját-adatból-illesztve" id="toc-dixon-coles-alacsony-gólszámú-korrekció-saját-adatból-illesztve" class="nav-link" data-scroll-target="#dixon-coles-alacsony-gólszámú-korrekció-saját-adatból-illesztve">Dixon-Coles alacsony-gólszámú korrekció, saját adatból illesztve</a></li>
  <li><a href="#fair-oddsok-az-első-fordulóra" id="toc-fair-oddsok-az-első-fordulóra" class="nav-link" data-scroll-target="#fair-oddsok-az-első-fordulóra">Fair oddsok az első fordulóra</a></li>
  <li><a href="#ázsiai-hendikep-ah-az-első-fordulóra" id="toc-ázsiai-hendikep-ah-az-első-fordulóra" class="nav-link" data-scroll-target="#ázsiai-hendikep-ah-az-első-fordulóra">Ázsiai hendikep (AH) az első fordulóra</a></li>
  </ul></li>
  <li><a href="#ismert-korlátok" id="toc-ismert-korlátok" class="nav-link" data-scroll-target="#ismert-korlátok">Ismert korlátok</a></li>
  <li><a href="#következő-lépések" id="toc-következő-lépések" class="nav-link" data-scroll-target="#következő-lépések">Következő lépések</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">NB1 előszezoni tabella-modell — Módszertani dokumentáció</h1>
<p class="subtitle lead">Szezon eleji over/under becslés csapatonként</p>
</div>

<div>
  <div class="description">
    Keretérték-alapú előszezoni pontszám-előrejelzés az NB1-ben: adatforrások, korlátok, modell.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 3, 2026</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="cél" class="level2">
<h2 class="anchored" data-anchor-id="cél">Cél</h2>
<p>Előszezoni (vagy szezon eleji) becslés az NB1 csapatainak várható teljesítményére — pontszám/mérkőzés formában —, hasonlóan ahhoz, ahogy a fogadóirodák preseason over/under vonalai működnek. <strong>Nem</strong> meccsenkénti kimenet-predikcióról van szó (ehhez nincs meccsszintű historikus adatunk), hanem arról, hogy a szezon <strong>elején ismert</strong> információból (elsősorban keretérték) milyen végső tabellahelyet/pontszámot várunk.</p>
</section>
<section id="miért-a-keretérték" class="level2">
<h2 class="anchored" data-anchor-id="miért-a-keretérték">Miért a keretérték?</h2>
<p>A keretérték → tabellahely összefüggés az egyik legjobban dokumentált jelenség a futballelemzésben (nagy ligákban jellemzően 0.6-0.8 körüli korrelációval). Ez azért jó kiindulópont, mert:</p>
<ul>
<li><strong>Szezon előtt is ismert</strong> — nem igényel in-season adatot.</li>
<li><strong>Nem igényel meccsszintű historikus adatot</strong>, csak a keret összetételét, amit a Transfermarkt archívumban visszamenőleg is meg lehet találni.</li>
<li>Az NB1-re szabott saját kalibrációt igényel (a nagy ligás összefüggés nem vehető át változtatás nélkül), ehhez viszont kell egy historikus minta a mi ligánkból.</li>
</ul>
</section>
<section id="adatforrások" class="level2">
<h2 class="anchored" data-anchor-id="adatforrások">Adatforrások</h2>
<section id="keretérték-transfermarkt" class="level3">
<h3 class="anchored" data-anchor-id="keretérték-transfermarkt">1. Keretérték — Transfermarkt</h3>
<p>A liga főoldala (<code>transfermarkt.com/.../startseite/wettbewerb/UNG1/saison_id/&lt;év&gt;</code>) csapatonként tartalmaz egy összesítő táblázatot: keretméret, átlagéletkor, légiósok száma, átlagos és <strong>összesített piaci érték</strong>. Ez egyetlen kéréssel megadja mind a 12 csapat adatát egy szezonra — nem kellett csapatonként külön scrape-elni.</p>
<p><strong>Fontos korlát a keretérték időzítéséről:</strong> a Transfermarkt archív szezon-oldala nem jelöl pontos naptári dátumot (“ez az érték ekkor és ekkor volt érvényes”). A piaci értéket egy szezon alatt jellemzően 3-6 alkalommal frissítik (kb. a válogatott szünetek környékén), és az archivált oldal a <strong>szezon alatti legutolsó frissítést</strong> mutatja — nagyjából “szezon vége felé” jellegű pillanatkép, nem egzakt dátum. Ellenőriztük egy konkrét játékoson (Dénes Dibusz, 2019/20: €950k), hogy ez valódi, akkori historikus érték, nem a mai piaci ár visszavetítése.</p>
<p>Ez a bizonytalanság a <strong>historikus visszateszteléshez nem probléma</strong> (konzisztens minden csapatra ugyanabból a szezonból), de a <strong>friss 2026-27-es predikcióhoz igen</strong> — ott a scrape időzítése (minél közelebb a szezonkezdéshez, az átigazolási ablak zárása előtt/után) számít. Ezt a következő lépésben véglegesítjük.</p>
<p>Négy szezon van begyűjtve: <strong>2022-23, 2023-24, 2024-25, 2025-26</strong> (script: <code>futball/scripts/scrape_tm_historical.R</code>).</p>
</section>
<section id="végeredmény-pontszám" class="level3">
<h3 class="anchored" data-anchor-id="végeredmény-pontszám">2. Végeredmény (pontszám)</h3>
<ul>
<li><strong>2024-25 és 2025-26</strong>: már megvolt a <code>team_stats</code> táblában (Wyscout-eredetű <code>Points</code> KPI, mérkőzésenkénti átlagként).</li>
<li><strong>2022-23 és 2023-24</strong>: a modell megírásakor még nem volt sehol a repóban. Az FBref-es lekérdezés (worldfootballR <code>fb_league_stats</code>) <strong>403 Forbidden</strong>-nel elutasított minden kérést (Cloudflare-szintű bot-védelem, nem csomag- vagy fejléc-probléma — plain <code>curl</code> is 403-at kapott). Megoldás: a Transfermarkt <strong>saját tabella-oldala</strong> (<code>transfermarkt.com/.../tabelle/wettbewerb/UNG1?saison_id=&lt;év&gt;</code>), ami ugyanazon domainen elérhető, és tartalmazza a Pl/W/D/L/GF:GA/Pts oszlopokat.
<ul>
<li><em>Frissítés</em>: a 2023-24-es szezon teljes Wyscout-KPI-készlete (a <code>Points</code>-szal együtt) azóta bekerült a <code>team_stats</code> táblába is. A két forrás (TM tabella-oldal vs.&nbsp;Wyscout <code>team_stats</code>) pont/meccs értékei kerekítési pontossággal megegyeznek — ez keresztellenőrzi mindkettőt. A <code>nb1_model_dataset.pts_per_match</code> (a fő keretérték-modellhez) továbbra is a TM-forrásból származik, változtatás nélkül; a 2023-24-es <code>team_stats</code>-adat újdonsága, hogy lehetővé teszi a lenti KPI-screening kiterjesztését egy második lag-párra (ld. “Előző szezoni forma-mutatók”).</li>
</ul></li>
</ul>
<p>Minden szezon 33 fordulóból áll (alapszakasz + felső-/alsóházi rájátszás), ezért a <code>pts_per_match</code> (pont/meccs) mint célváltozó közvetlenül összevethető a <code>team_stats</code>-beli, már eleve mérkőzésenkénti átlagként tárolt <code>Points</code> értékkel.</p>
</section>
<section id="csapatnév-egyeztetés" class="level3">
<h3 class="anchored" data-anchor-id="csapatnév-egyeztetés">3. Csapatnév-egyeztetés</h3>
<p>A Transfermarkt három különböző névformátumot használ ugyanarra a csapatra a különböző oldaltípusokon (pl. “Puskás Akadémia FC” a keretérték-táblán, “Puskás AFC” a tabella-oldalon), és időben is változik (pl. “Fehérvár FC” → “Videoton FC Fehérvár”; “Kisvárda FC” → a Wyscout-oldalon már “Várda SE”). A <code>futball/data/team_name_mapping.csv</code> fájl tartalmazza az összes eddig előkerült variánst → a <code>team_stats</code>-ban használt kanonikus névre képezve. Verein ID-alapon (pl. Kisvárda: <code>verein/30613</code>) ellenőriztük, hogy azonos klubról van szó a névváltozások mögött.</p>
</section>
</section>
<section id="az-egyesített-adatkészlet" class="level2">
<h2 class="anchored" data-anchor-id="az-egyesített-adatkészlet">Az egyesített adatkészlet</h2>
<p><code>futball.db</code> → <code>nb1_model_dataset</code> tábla, 48 csapat-szezon sor (12 csapat × 4 szezon), oszlopok: <code>szezon</code>, <code>team</code>, <code>total_market_value_euro</code>, <code>avg_age</code>, <code>squad_size</code>, <code>foreigners</code>, <code>pts_per_match</code>, <code>promoted</code> (bináris: az adott csapat nem volt bent NB1-ben az előző szezonban).</p>
</section>
<section id="modell" class="level2">
<h2 class="anchored" data-anchor-id="modell">Modell</h2>
<section id="alapmodell" class="level3">
<h3 class="anchored" data-anchor-id="alapmodell">Alapmodell</h3>
<p><span class="math display">\[
\text{pts\_per\_match} = \beta_0 + \beta_1 \cdot \log(\text{átlagos játékosérték}) + \varepsilon
\]</span></p>
<p><strong>Miért az átlagos játékosérték, és nem az összesített keretérték?</strong> Mindkettőt teszteltük — az átlagérték minden mérésben jobbnak bizonyult: magasabb önálló R² (0.535 vs 0.465), és a walk-forward validáció mindhárom kihagyott szezonon konzisztensen alacsonyabb hibát adott (ld. lejjebb). Ennek valószínű oka, hogy az összesített keretméret torzulhat a kerethossztól — egy nagyobb, átlagos játékosokkal feltöltött keret felfújja az összeget anélkül, hogy a kezdőcsapat minősége nőne, míg az átlagérték inkább a “minőségi koncentrációt” ragadja meg.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = pts_per_match ~ log_value, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.52879 -0.14517 -0.00765  0.11983  0.51449 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -5.67595    0.96994  -5.852 4.83e-07 ***
log_value    0.55667    0.07656   7.271 3.58e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2661 on 46 degrees of freedom
Multiple R-squared:  0.5347,    Adjusted R-squared:  0.5246 
F-statistic: 52.87 on 1 and 46 DF,  p-value: 3.58e-09</code></pre>
</div>
</div>
<p><strong>N = 48</strong>, R² = 0.535, a <code>log_value</code> (átlagos játékosérték) együttható erősen szignifikáns (p &lt; 0.0001). A korreláció <strong>0.73</strong> — ez az NB1-re jellemző, a más ligákra dokumentált 0.6-0.8-as sávba illeszkedik.</p>
</section>
<section id="feljutó-csapat-dummy" class="level3">
<h3 class="anchored" data-anchor-id="feljutó-csapat-dummy">Feljutó csapat dummy</h3>
<p>A feljutó csapatokra (n=4 a mintában: Diósgyőr 23/24, Győri ETO és Nyíregyháza 24/25, Kazincbarcika 25/26, Várda SE 25/26) hozzáadott bináris változó <strong>nem szignifikáns</strong> (p = 0.94), és nem javítja az illeszkedést. Ez azt jelzi, hogy a feljutók historikusan gyengébb teljesítménye ebben a mintában már teljesen a (jellemzően alacsonyabb) keretértéken keresztül érvényesül — külön “feljutó-büntetés” nem szükséges, <strong>de a mintaelemszám (n=4) miatt ez a következtetés bizonytalan</strong>, később több szezonnal érdemes újranézni.</p>
<p><strong>A végleges modell egyelőre az egyszerű <code>pts_per_match ~ log(átlagos játékosérték)</code> (Modell 1).</strong></p>
</section>
<section id="validáció-walk-forward-expanding-window-nem-leave-one-season-out" class="level3">
<h3 class="anchored" data-anchor-id="validáció-walk-forward-expanding-window-nem-leave-one-season-out">Validáció — walk-forward (expanding window), nem leave-one-season-out</h3>
<p><strong>Miért nem leave-one-season-out (LOSO)?</strong> Első nekifutásra LOSO-val validáltunk (minden szezont kihagyva, a maradék hármon tanítva). Ez feature-szivárgás értelmében nem hibás — minden sor önmagában áll, egy adott szezon keretértéke csak az adott szezon pontszámát jósolja, nincs jövőbeli oszlop egy múltbeli sorban. <strong>De éles bevetési realizmus szempontjából mégis hibás volt</strong>: LOSO megengedte, hogy pl. a 2023-24, 2024-25 és 2025-26 szezonokból tanulva jósoljuk meg a 2022-23-at — ez a valóságban soha nem történhetne meg, hiszen a 2022-23-as predikció idején a későbbi szezonok adata még nem létezett. A szezonok időben egymásra épülnek, nem cserélhető fel a sorrendjük.</p>
<p>A helyes teszt: <strong>csak a múltból tanulva jósold a következő szezont</strong> (expanding window / walk-forward).</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Walk-forward out-of-sample hiba: átlagos vs.&nbsp;összesített keretérték</caption>
<thead>
<tr class="header">
<th style="text-align: left;">prediktor</th>
<th style="text-align: left;">joslas</th>
<th style="text-align: right;">RMSE</th>
<th style="text-align: right;">OOS_R2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">atlagos jatekosertek</td>
<td style="text-align: left;">2023-24</td>
<td style="text-align: right;">0.246</td>
<td style="text-align: right;">0.617</td>
</tr>
<tr class="even">
<td style="text-align: left;">atlagos jatekosertek</td>
<td style="text-align: left;">2024-25</td>
<td style="text-align: right;">0.297</td>
<td style="text-align: right;">0.452</td>
</tr>
<tr class="odd">
<td style="text-align: left;">atlagos jatekosertek</td>
<td style="text-align: left;">2025-26</td>
<td style="text-align: right;">0.271</td>
<td style="text-align: right;">0.560</td>
</tr>
<tr class="even">
<td style="text-align: left;">osszesitett keretertek</td>
<td style="text-align: left;">2023-24</td>
<td style="text-align: right;">0.267</td>
<td style="text-align: right;">0.547</td>
</tr>
<tr class="odd">
<td style="text-align: left;">osszesitett keretertek</td>
<td style="text-align: left;">2024-25</td>
<td style="text-align: right;">0.319</td>
<td style="text-align: right;">0.370</td>
</tr>
<tr class="even">
<td style="text-align: left;">osszesitett keretertek</td>
<td style="text-align: left;">2025-26</td>
<td style="text-align: right;">0.296</td>
<td style="text-align: right;">0.476</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Csak <strong>3 tesztpont</strong> van szezononként (nem 4, mert az első szezon előtt nincs múlt, amiből tanulni lehetne) — ez a valódi ára annak, hogy csak 4 szezonunk van. Az <strong>átlagos játékosérték mindhárom kihagyott szezonon jobb</strong> (alacsonyabb RMSE, magasabb OOS-R²), mint az összesített keretérték — ez nem véletlen egyszeri csúcs, hanem konzisztens előny, ezért lett ez a végleges elsődleges prediktor.</p>
<p><strong>Feltűnő kiugrások</strong>: Győri ETO 2025-26-ban jócskán felülteljesítette a keretérték alapján várt pontszámot (+0.57 pont/meccs), Fehérvár 2024-25-ben jelentősen alulteljesített (-0.55). Ezek jelzik, hogy a keretérték önmagában nem magyaráz mindent — edzőváltás, szezon közbeni forma, sérülések stb. nincsenek a modellben.</p>
</section>
</section>
<section id="kiegészítő-prediktorok-szisztematikus-átvizsgálás" class="level2">
<h2 class="anchored" data-anchor-id="kiegészítő-prediktorok-szisztematikus-átvizsgálás">Kiegészítő prediktorok — szisztematikus átvizsgálás</h2>
<p>Mielőtt lezárnánk az alapmodellt, végigmentünk azon, mi másból lehetne még prediktív erőt nyerni. (Az átlagos vs.&nbsp;összesített keretérték összevetése már a fenti “Alapmodell” szakaszban megtörtént — ott dőlt el, hogy az átlagérték a jobb választás.)</p>
<section id="előző-szezoni-forma-mutatók-lag-és-a-többszörös-összehasonlítás-csapdája" class="level3">
<h3 class="anchored" data-anchor-id="előző-szezoni-forma-mutatók-lag-és-a-többszörös-összehasonlítás-csapdája">Előző szezoni forma-mutatók (lag), és a többszörös összehasonlítás csapdája</h3>
<p><strong>Frissítve a 2022-23-as szezon <code>team_stats</code> adatainak bekerülésével.</strong> Korábban ez a screening két lépcsőben bővült: eleinte csak a 2024-25 → 2025-26 eltolást tudta használni (N=10), majd a 2023-24-es KPI-k bekerülésével N=20-ra nőtt (2023-24 → 2024-25 és 2024-25 → 2025-26 pool-olva). Most, hogy a 2022-23-as csapat-KPI-k is bekerültek az adatbázisba, <strong>három lag-párt tudunk pool-olni</strong>: 2022-23 → 2023-24, 2023-24 → 2024-25 és 2024-25 → 2025-26, egyenként N=10 csapattal, összesen <strong>N=30</strong>. Ez azért fontos, mert most már <strong>két valódi, időrendi walk-forward tesztpontunk</strong> van (nem csak egy), így a lenti “Igazi walk-forward teszt” szakasz eredménye jóval megbízhatóbb, mint korábban.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Tesztelt KPI-k száma: 85 | pool-olt N: 30 ( 10 + 10 + 10 )</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 78%">
<col style="width: 3%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">kpi</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">r2</th>
<th style="text-align: right;">cor</th>
<th style="text-align: right;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">chancecreation__Box touches</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.522</td>
<td style="text-align: right;">0.723</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">attackingtransition__xG within 10s after recovery</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.519</td>
<td style="text-align: right;">0.720</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">attack__xT</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.469</td>
<td style="text-align: right;">0.685</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">attackingtransition__Recovery line height (m)</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.448</td>
<td style="text-align: right;">0.670</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">attack__Field tilt %</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.445</td>
<td style="text-align: right;">0.667</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">overallperformance__Field tilt %</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.445</td>
<td style="text-align: right;">0.667</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">attackingtransition__Possessions retained after 5s</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.426</td>
<td style="text-align: right;">0.653</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">chancecreation__np xG</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.425</td>
<td style="text-align: right;">0.652</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">attackingtransition__Possessions to box within 10s after recovery</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.424</td>
<td style="text-align: right;">0.651</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">attackingtransition__Recoveries</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.416</td>
<td style="text-align: right;">0.645</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Fontos módszertani figyelmeztetés (frissítve)</strong>: 85 mutatót teszteltünk, most már N=30-on (nem N=20-on, nem N=10-en). Az |r|&gt;0.3 küszöböt 48 a 78-ből lépte át, p&lt;0.05 szinten 45 maradt szignifikáns — a többszörös összehasonlítás csapdája N=30-on is fennáll, csak kevésbé súlyosan, mint N=20-on vagy N=10-en.</p>
<p><strong>A rangsor korábban (N=10→N=20) érdemben átrendeződött, N=20→N=30 között viszont már stabil maradt</strong> — a <code>Box touches</code> (chancecreation) mindkét bővítés után a top helyen maradt, ami önmagában megerősíti, hogy ez nem véletlen egyszeri csúcs volt. Az <code>Opp. Possessions to final third %</code> és az <code>Opp. xT</code> továbbra is lejjebb csúszott N=30-on — ez megerősíti a korábbi gyanút, hogy ezek nagyrészt a keretérték zajos újrafogalmazásai voltak, nem önálló jelzések.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 53%">
<col style="width: 3%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">kpi</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">full_r2</th>
<th style="text-align: right;">loo_min</th>
<th style="text-align: right;">loo_max</th>
<th style="text-align: right;">cor_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">chancecreation__Box touches</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.522</td>
<td style="text-align: right;">0.457</td>
<td style="text-align: right;">0.591</td>
<td style="text-align: right;">0.773</td>
</tr>
<tr class="even">
<td style="text-align: left;">chancecreation__np Shots</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.384</td>
<td style="text-align: right;">0.327</td>
<td style="text-align: right;">0.450</td>
<td style="text-align: right;">0.656</td>
</tr>
<tr class="odd">
<td style="text-align: left;">defence__Opp. Possessions to final third %</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.411</td>
<td style="text-align: right;">0.334</td>
<td style="text-align: right;">0.498</td>
<td style="text-align: right;">-0.452</td>
</tr>
<tr class="even">
<td style="text-align: left;">defence__Opp. xT</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.352</td>
<td style="text-align: right;">0.286</td>
<td style="text-align: right;">0.429</td>
<td style="text-align: right;">-0.684</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li><strong><code>Box touches</code> (chancecreation, előző szezon)</strong>: a legerősebb pool-olt jelölt, és <strong>stabil maradt mindhárom N-en</strong> (N=10 → N=20 → N=30), miközben a mezőny többi tagja átrendeződött körülötte — ez önmagában erős jel, hogy nem véletlen csúcs. N=30-on: R²=0.522, leave-one-out tartomány 0.457-0.591 — tovább szűkült N=20-hoz (0.50-0.62) képest, azaz még stabilabb.</li>
<li><strong><code>Opp. xT</code></strong>: R²-je tovább esett, 0.551 (N=10) → 0.399 (N=20) → 0.352 (N=30). A monoton csökkenés minden bővítésnél megerősíti a korábbi gyanút, hogy nagyrészt a keretérték zajos újrafogalmazása volt (kollinearitás a keretértékkel: -0.68).</li>
<li><strong><code>Opp. Possessions to final third %</code></strong>: R²=0.411 (N=30) — nagyjából a korábbi N=20-as szinten (0.447) stabilizálódott, továbbra is középmezőnyben marad, egyik bővítés sem söpörte le, de a <code>Box touches</code>-t sosem érte utol.</li>
</ul>
<p><strong>Ad hozzá önálló prediktív erőt a keretértékhez képest?</strong> Ugyanezen a pool-olt N=30 mintán a keretérték önmagában R²=0.318 (alacsonyabb, mint a teljes 48 soros mintán mért 0.535 — a lag-minta csak azokra a csapatokra szűkít, amik két egymást követő szezonban is bent maradtak NB1-ben, ami leszűkíti a keretérték-szórást). A <code>Box touches</code> hozzáadva a keretértékhez:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Csak keretérték          R²: 0.318 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Keretérték + Box touches R²: 0.523 | Box touches p-érték: 0.0021 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>log_value együttható a kombinált modellben: 0.011 (p = 0.951 ) — nem szignifikáns</code></pre>
</div>
</div>
<p>A <code>Box touches</code> szignifikáns marad a keretérték mellett is (p≈0.002), de a kombinált modell R²-je (0.523) gyakorlatilag <strong>nem magasabb</strong>, mint a <code>Box touches</code> önmagában (0.522) — a keretérték saját együtthatója N=30-on már szinte teljesen eltűnik (p≈0.95, a koefficiens ≈0.01-re zsugorodik). N=20-on ez még “csak” nem-szignifikáns volt (p≈0.37); N=30-on már gyakorlatilag nulla a hozzáadott értéke. Ez a két mutató közötti erős kollinearitásra utal (r=0.77 a <code>Box touches</code> és log(keretérték) között), és arra, hogy <strong>a <code>Box touches</code> a nagyobb mintán önmagában lefedi mindazt, amit a keretérték a jövő szezon pontszámáról elárul</strong> — nem azért, mert a keretértéknek nincs hatása, hanem mert a <code>Box touches</code> már tartalmazza ugyanazt az információt, méghozzá frissebb, közvetlenebb formában.</p>
<p><strong>Vajon a <code>Box touches</code> tényleg jobb, mint az olyan “szofisztikáltabb” mutatók, mint az xG-differencia vagy az xT-differencia?</strong> Első ránézésre meglepő lenne, ha egy egyszerű érintésszám-mutató verné a minőség-korrigált várható gól- és fenyegetettségi mutatókat. Két dolgot érdemes szétválasztani: (1) ugyanazt az alapjelenséget mérik-e, és (2) melyik <strong>jósolja be ténylegesen jobban</strong> a következő szezont — ez utóbbi kérdésre a helyes válasz csak közvetlen walk-forward teszttel adható meg, nem a mutató önmagával vett év-évi stabilitásából (ld. lentebb, a “Következtetés” felülvizsgálva).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Korreláció a három jelölt között (azonos szezoni, N=48):</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          box xg_diff xt_diff
box     1.000   0.875   0.889
xg_diff 0.875   1.000   0.915
xt_diff 0.889   0.915   1.000</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Évről évre stabilitás (saját mutató t szezonban -&gt; saját mutató t+1 szezonban):</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  kpi         n ev_rol_evre_r
  &lt;chr&gt;   &lt;int&gt;         &lt;dbl&gt;
1 box        30         0.766
2 xg_diff    30         0.682
3 xt_diff    30         0.745</code></pre>
</div>
</div>
<p>Két megállapítás:</p>
<ol type="1">
<li><strong>A három mutató erősen kollineáris egymással</strong> (r=0.87-0.92, azonos szezoni összevetésben) — vagyis nem arról van szó, hogy a <code>Box touches</code> valami teljesen más, addig rejtett jelenséget ragadna meg, mint az xG-diff vagy xT-diff. Mindhárom lényegében ugyanazt az alapjelenséget méri (a csapat területi/támadási dominanciáját), csak eltérő kifinomultsággal.</li>
<li><strong>A <code>Box touches</code> évről évre stabilabb</strong> (year-over-year r=0.77) <strong>, mint az xG-diff (r=0.68) vagy az xT-diff (r=0.75)</strong> — de ez a saját-magával-vett stabilitás <strong>nem ugyanaz</strong>, mint a <em>következő szezon pontszámának</em> előrejelzési képessége. Ezt a különbséget korábban ez a dokumentum összemosta — helyesen csak egy közvetlen walk-forward teszt tudja eldönteni, melyik mutató jósol jobban, ld. lent.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Walk-forward OOS R² — Box touches vs.&nbsp;xT-diff vs.&nbsp;xG-diff, mint önálló lag-prediktor</caption>
<thead>
<tr class="header">
<th style="text-align: left;">modell</th>
<th style="text-align: right;">2023-24 -&gt; 2024-25</th>
<th style="text-align: right;">2024-25 -&gt; 2025-26</th>
<th style="text-align: right;">atlag</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Box touches (lag)</td>
<td style="text-align: right;">0.298</td>
<td style="text-align: right;">0.613</td>
<td style="text-align: right;">0.456</td>
</tr>
<tr class="even">
<td style="text-align: left;">xT-diff (lag)</td>
<td style="text-align: right;">0.557</td>
<td style="text-align: right;">0.504</td>
<td style="text-align: right;">0.530</td>
</tr>
<tr class="odd">
<td style="text-align: left;">xG-diff (lag)</td>
<td style="text-align: right;">0.457</td>
<td style="text-align: right;">0.400</td>
<td style="text-align: right;">0.428</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Ez megváltoztatja a korábbi következtetést.</strong> Amikor a három jelöltet közvetlenül, azonos walk-forward protokollal összevetjük (nem csak a saját-magukkal vett stabilitásukat nézzük), az <strong>xT-diff nyer</strong>: átlagos OOS R²=0.531, és a két tesztponton is szorosan együtt (0.557 és 0.504) — sokkal stabilabb előrejelzési teljesítmény, mint a <code>Box touches</code>-é (0.298 és 0.613 között ingadozik, átlag 0.455). Az xG-diff a leggyengébb (átlag 0.429), valószínűleg mert az xG mint mutató két külön becslés (lövés + minőség-súlyozás) szorzata, ami extra zajréteget ad hozzá.</p>
<p><strong>Következtetés (felülvizsgálva)</strong>: a korábbi verzió tévesen azonosította a “évről évre önmagával vett stabilitást” a “jövőbeli pontszám-előrejelzési képességgel”. Amikor ezt közvetlenül teszteljük, az <strong>xT-diff a legjobb önálló lag-prediktor</strong> a visszatérő csapatokra, nem a <code>Box touches</code>. A teljes minta (N=48, azonos szezoni) <code>log(keretérték)</code>-modellje továbbra is az elsődleges, amikor a kérdés a jelen szezonra vonatkozik — a jövő szezon becslésénél pedig (ld. lentebb, végleges modell) a kontemporán keretértéket és az xT-diffet <strong>kombináljuk</strong>, mert két, egymástól részben független infoforrást ragadnak meg (idei keretminőség vs.&nbsp;tavalyi tényleges játékstílus), és a kombinált modell konceptuálisan erősebb, gyakorlatilag pedig nem gyengébb, mint bármelyik önmagában (ld. “Végleges modell” szakasz).</p>
</section>
<section id="pénzügyi-mutatók-bevétel-és-személyi-jellegű-ráfordítás" class="level3">
<h3 class="anchored" data-anchor-id="pénzügyi-mutatók-bevétel-és-személyi-jellegű-ráfordítás">Pénzügyi mutatók: bevétel és személyi jellegű ráfordítás</h3>
<p>A <code>team_finances</code> tábla (forrás: beszámoló-kigyűjtés, <code>futball/scripts/build_finances.R</code>) NB1-es klubok “Összesen” bevétel- és “Személyi jellegű ráfordítás” sorait is tartalmazza. Mivel a legtöbb nagy NB1-es klub naptári év szerint (nem szezon szerint) jelent, a <code>team_finances_season</code> tábla szezon-szintű nézetet épít: ahol van közvetlen szezon-formátumú beszámoló (pl. “22/23”), azt használja; ahol nincs, ott a szezont lefedő két naptári év (pl. 2024 és 2025 → “2024-25”) átlagával közelíti.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>N: 36 | szezonok:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
2022-23 2023-24 2024-25 
     12      12      12 </code></pre>
</div>
</div>
<p><strong>Azonos szezoni (kortárs) modellek:</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>log_value       R2=0.524  cor=0.724  p=0.0000
log_revenue     R2=0.351  cor=0.592  p=0.0001
log_personnel   R2=0.328  cor=0.573  p=0.0003</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Kollináció a prediktorok között:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>              log_value log_revenue log_personnel
log_value     1.0000000   0.8091566     0.8286484
log_revenue   0.8091566   1.0000000     0.9650240
log_personnel 0.8286484   0.9650240     1.0000000</code></pre>
</div>
</div>
<p>Mindkét pénzügyi mutató önmagában is szignifikáns, de a keretértéknél (R²≈0.52-0.56) gyengébb: a bevétel R²≈0.29-0.35, a személyi ráfordítás R²≈0.25-0.33 (a pontos érték attól függ, 2 vagy 3 szezonos mintán számoljuk). Mindkettő erősen kollineáris a keretértékkel (r≈0.81-0.83) és egymással (r≈0.96) — logikus, hiszen a bérköltség a bevétel nagy részét felemészti.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>keretérték + bevétel — log_revenue p-érték: 0.9300848 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>keretérték + szem. ráfordítás — log_personnel p-érték: 0.6853689 </code></pre>
</div>
</div>
<p>Kétváltozós modellben (keretérték + bevétel, ill.&nbsp;+ személyi ráfordítás) egyik pénzügyi mutató együtthatója sem szignifikáns a keretérték mellett (p&gt;0.9, ill.&nbsp;p&gt;0.6) — <strong>önálló prediktív erőt nem adnak hozzá</strong>.</p>
<p><strong>Lag-teszt — az egyetlen módszertanilag tiszta kérdés</strong>: a fentiek kortárs (azonos szezoni) összevetések, ahol a bérköltség/bevétel részben már a szezon közbeni teljesítményt (sikerbónuszok, formától függő erősítés) is tükrözi — ez nem előrejelzés, hanem együttmozgás. A helyes preseason-teszt: az <strong>N. szezon lezárt beszámolójából</strong> jósoljuk az <strong>N+1. szezon</strong> pontszámát.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>N: 24 | log(szemelyi_prev) R2: 0.4616323 | cor: 0.6794353 | p: 0.0002608358 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Walk-forward (train 22/23→23/24, test 23/24→24/25) OOS R²: 0.3692647 </code></pre>
</div>
</div>
<p>N=24: az előző szezoni személyi ráfordítás R²=0.462 (cor=0.68, p&lt;0.001), walk-forward OOS R²=0.37. Ez érdemben <strong>gyengébb, mint az azonos szezoni</strong> összefüggés (R²≈0.57) — vagyis a bérköltség egy jelentős része valóban együtt mozog a szezon közbeni sikerrel, nem pusztán előre jelzi azt. Ugyanakkor a lag-verzióban is marad valódi (nem visszamenőleges) prediktív erő, csak a keretértéknél gyengébb.</p>
<p><strong>Következtetés</strong>: sem a bevétel, sem a személyi jellegű ráfordítás nem versenyképes helyettesítője vagy kiegészítője a keretértéknek — inkább a klub gazdasági méretének indikátorai, mint a versenyképességéé, és a kortárs (nem lag) verziójuk prediktív ereje jelentős részben a szezon közbeni teljesítménnyel való együttmozgásból, nem valódi előrejelzésből ered.</p>
</section>
<section id="miért-nincs-még-többváltozós-modell" class="level3">
<h3 class="anchored" data-anchor-id="miért-nincs-még-többváltozós-modell">Miért nincs (még) többváltozós modell</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>N: 10 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Ket-valtozos modell R²: 0.7070437 | log_avg_value (elozo szezon) p-erteke: 0.9972389 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>(Onmagaban az elozo szezoni keretertek erre a 10 csapatra R² = 0.2632625 )</code></pre>
</div>
</div>
<p>Amikor a keretértéket és az <code>Opp. Possessions to final third %</code>-ot <strong>együtt</strong> tesszük egy modellbe (N=10), a keretérték együtthatója <strong>elveszti a szignifikanciáját</strong> — a két mutató nagyrészt ugyanazt az információt hordozza ezen a kis mintán, és nem tisztességes összevetni őket, mert nem is ugyanazon a mintán lettek mérve (a keretérték-modell N=48-on, a KPI-alapú N=10-en). Egy három-változós “mindent bele” modellen (keretérték + két KPI, N=10, df=6) az R² látszólag 0.94-re ugrik — de eközben a <strong>keretérték együtthatója előjelet vált negatívra</strong>, ami a klasszikus túlillesztés tünete. Ez a szám nem valódi.</p>
<p><strong>Következtetés</strong>: N=10-zel egynél több paramétert becsülni statisztikailag megbízhatatlan. <strong>A ténylegesen vállalható modell egyelőre az egyváltozós <code>pts_per_match ~ log(átlagos játékosérték)</code></strong> (N=48). Az <code>Opp. Possessions to final third %</code> és az xT-különbség ígéretes jelöltek egy jövőbeli, több szezonra kiterjedő bővítéshez, de egyelőre nem építhetők be felelősen.</p>
</section>
</section>
<section id="végleges-modell-és-2026-27-előrejelzés" class="level2">
<h2 class="anchored" data-anchor-id="végleges-modell-és-2026-27-előrejelzés">Végleges modell és 2026-27 előrejelzés</h2>
<section id="miért-nem-a-naiv-többmodell-átlag-és-miért-nem-külön-feljutó-modell" class="level3">
<h3 class="anchored" data-anchor-id="miért-nem-a-naiv-többmodell-átlag-és-miért-nem-külön-feljutó-modell">Miért nem a naiv többmodell-átlag, és miért nem külön feljutó-modell</h3>
<p>Ez a szakasz korábban két külön, egymástól függetlenül illesztett modell egyenlő súlyú átlagát használta a visszatérő csapatokra (keretérték + <code>Box touches</code>), és egy bespoke NB2-kalibrációt a feljutókra. Mindkettőt felülvizsgáltuk, mert konkrét teszttel jobb megoldás igazolható:</p>
<ol type="1">
<li><strong>A visszatérőknél nem a <code>Box touches</code>, hanem az xT-diff a legjobb önálló lag-prediktor</strong> (ld. fenti “Kiegészítő prediktorok” szakasz felülvizsgált következtetése) — a korábbi “Box touches nyer” állítás a mutató önmagával vett stabilitását keverte össze a tényleges előrejelző erővel. Emellett most már <strong>megvan a friss, kontemporán 2026-27-es keretérték</strong> is (korábban ez hiányzott, ezért kellett lag-proxykra hagyatkozni) — ezt nem szabad kihagyni, hiszen ez a legerősebb egyváltozós prediktorunk (R²=0.535, N=48).</li>
<li><strong>A feljutókra épített külön NB2-kalibráció (N=6) rosszabb, mint a sima, nagy mintás keretérték-modell.</strong> Visszateszteltük: a kontemporán keretérték-modell (<code>m1</code>, N=48-on illesztve) a hat történelmi feljutóra RMSE=0.187-et ad, míg a saját N=6-os NB2-kalibrációnk RMSE=0.267-et (ami ráadásul in-sample szám, a valós hibája még nagyobb lenne). Amikor az NB2-pontszámot hozzáadtuk a keretértékhez egy kombinált N=6-os modellben, az együtthatója <strong>negatívvá és nem szignifikánssá</strong> vált — klasszikus túlillesztés ekkora mintán. <strong>A feljutó-dummy korábbi (nem szignifikáns) eredménye pontosan ezt jósolta előre</strong>: nincs szükség külön feljutó-modellre, a keretérték-modell magától is jól általánosít rájuk.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Végső jelölt modellek walk-forward OOS R²-je</caption>
<colgroup>
<col style="width: 42%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">modell</th>
<th style="text-align: right;">2023-24 -&gt; 2024-25</th>
<th style="text-align: right;">2024-25 -&gt; 2025-26</th>
<th style="text-align: right;">atlag</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">keretérték (kontemp.)</td>
<td style="text-align: right;">0.452</td>
<td style="text-align: right;">0.434</td>
<td style="text-align: right;">0.443</td>
</tr>
<tr class="even">
<td style="text-align: left;">xT-diff (lag)</td>
<td style="text-align: right;">0.557</td>
<td style="text-align: right;">0.504</td>
<td style="text-align: right;">0.530</td>
</tr>
<tr class="odd">
<td style="text-align: left;">keretérték + xT-diff (végleges)</td>
<td style="text-align: right;">0.503</td>
<td style="text-align: right;">0.526</td>
<td style="text-align: right;">0.514</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Végleges modell (N=30, teljes mintán illesztve):</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                    Estimate Std. Error   t value   Pr(&gt;|t|)
(Intercept)       -3.0757993  1.6812715 -1.829448 0.07839688
log_value_current  0.3498099  0.1322259  2.645547 0.01343179
xt_diff            0.3960213  0.1581425  2.504205 0.01861487</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>In-sample R²: 0.637 </code></pre>
</div>
</div>
<p>A kombinált modell (0.514 átlagos OOS R²) gyakorlatilag megegyezik az önálló xT-diff (0.531) teljesítményével — ekkora mintán (N=30) ez a különbség zajszinten belül van, statisztikailag nem választható szét. A kombinált modellt választjuk <strong>nem azért, mert bizonyítottan jobb</strong>, hanem mert két, egymástól részben független infoforrást ragad meg (idei keretminőség + tavalyi tényleges játékstílus), és mindkét együttható szignifikáns marad a másik mellett (p&lt;0.02) — ez konceptuálisan robusztusabbá teszi, mint egy egyváltozós modellt, anélkül, hogy a “mindent bele” (3+ prediktoros) verzió túlillesztési kockázatát futná.</p>
</section>
<section id="a-feljutók-keretérték-modell-nb2-mint-leíró-kontextus" class="level3">
<h3 class="anchored" data-anchor-id="a-feljutók-keretérték-modell-nb2-mint-leíró-kontextus">A feljutók: keretérték-modell + NB2 mint leíró kontextus</h3>
<p>A <strong>Vasas</strong> és a <strong>Kispest-Honvéd</strong> NB2-es búcsúszezonja (<code>futball/data/nb2_promoted_teams_history.csv</code>) nem hajt önálló számot, de fontos kontextus:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Feljutó csapatok NB2-es búcsúszezonja (2022-23 óta, mind a hat)</caption>
<colgroup>
<col style="width: 27%">
<col style="width: 13%">
<col style="width: 22%">
<col style="width: 16%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Csapat</th>
<th style="text-align: left;">NB2 szezon</th>
<th style="text-align: left;">NB1 szezon (köv.)</th>
<th style="text-align: right;">NB2 helyezés</th>
<th style="text-align: right;">NB2 pont/meccs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Diósgyőr</td>
<td style="text-align: left;">2022-23</td>
<td style="text-align: left;">2023-24</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.289</td>
</tr>
<tr class="even">
<td style="text-align: left;">MTK</td>
<td style="text-align: left;">2022-23</td>
<td style="text-align: left;">2023-24</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.947</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nyíregyháza Spartacus</td>
<td style="text-align: left;">2023-24</td>
<td style="text-align: left;">2024-25</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.324</td>
</tr>
<tr class="even">
<td style="text-align: left;">Győri ETO</td>
<td style="text-align: left;">2023-24</td>
<td style="text-align: left;">2024-25</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.029</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Várda SE</td>
<td style="text-align: left;">2024-25</td>
<td style="text-align: left;">2025-26</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.933</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kazincbarcika</td>
<td style="text-align: left;">2024-25</td>
<td style="text-align: left;">2025-26</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.767</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Vasas</td>
<td style="text-align: left;">2025-26</td>
<td style="text-align: left;">2026-27</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.133</td>
</tr>
<tr class="even">
<td style="text-align: left;">Honvéd</td>
<td style="text-align: left;">2025-26</td>
<td style="text-align: left;">2026-27</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.967</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A hat feljutóból <strong>egy esett ki egyből</strong> (Kazincbarcika, egyetlen NB1-szezon után vissza NB2-be) — ő volt egyúttal a leggyengébb NB2-es pont/meccsel (1.77) a hat közül is. Vasas (2.13 pont/meccs, NB2-bajnok) és Honvéd (1.97, NB2 2. helyezett) ennél jóval erősebb NB2-es búcsúszezonnal jött fel, tehát a Kazincbarcika-féle azonnali-kiesés veszélyzónájába nem sorolhatók egyértelműen — de ez csak leíró jelzés, nem a végső becslés bemenete (ld. fent, miért nem önálló modell).</p>
</section>
<section id="végleges-egyesített-2026-27-tábla" class="level3">
<h3 class="anchored" data-anchor-id="végleges-egyesített-2026-27-tábla">Végleges egyesített 2026-27 tábla</h3>
<p>Mind a 12 csapatra ugyanazt a modellcsaládot alkalmazzuk: a 10 visszatérőre a fenti kombinált (<code>m_final</code>) modellt (friss 2026-27 keretérték + 2025-26-os xT-diff), a 2 feljutóra pedig ugyanennek a keretérték-tagját (<code>m1</code>, hiszen nincs NB1-es xT-diff-előzményük).</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>26/27 végleges előrejelzett tabella — egységes modellcsalád mind a 12 csapatra</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 15%">
<col style="width: 25%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">team</th>
<th style="text-align: right;">Becsült pont/meccs</th>
<th style="text-align: right;">Becsült pontszám (33 meccsre)</th>
<th style="text-align: left;">Forrás</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ferencváros</td>
<td style="text-align: right;">2.031</td>
<td style="text-align: right;">67</td>
<td style="text-align: left;">keretérték (26-27) + xT-diff (25-26)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Győri ETO</td>
<td style="text-align: right;">1.842</td>
<td style="text-align: right;">61</td>
<td style="text-align: left;">keretérték (26-27) + xT-diff (25-26)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Paksi FC</td>
<td style="text-align: right;">1.492</td>
<td style="text-align: right;">49</td>
<td style="text-align: left;">keretérték (26-27) + xT-diff (25-26)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Puskás FC</td>
<td style="text-align: right;">1.460</td>
<td style="text-align: right;">48</td>
<td style="text-align: left;">keretérték (26-27) + xT-diff (25-26)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Újpest</td>
<td style="text-align: right;">1.415</td>
<td style="text-align: right;">47</td>
<td style="text-align: left;">keretérték (26-27) + xT-diff (25-26)</td>
</tr>
<tr class="even">
<td style="text-align: left;">MTK</td>
<td style="text-align: right;">1.345</td>
<td style="text-align: right;">44</td>
<td style="text-align: left;">keretérték (26-27) + xT-diff (25-26)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Debrecen</td>
<td style="text-align: right;">1.278</td>
<td style="text-align: right;">42</td>
<td style="text-align: left;">keretérték (26-27) + xT-diff (25-26)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nyíregyháza Spartacus</td>
<td style="text-align: right;">1.232</td>
<td style="text-align: right;">41</td>
<td style="text-align: left;">keretérték (26-27) + xT-diff (25-26)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Várda SE</td>
<td style="text-align: right;">1.198</td>
<td style="text-align: right;">40</td>
<td style="text-align: left;">keretérték (26-27) + xT-diff (25-26)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Vasas</td>
<td style="text-align: right;">1.154</td>
<td style="text-align: right;">38</td>
<td style="text-align: left;">keretérték (26-27) — csak m1, nincs NB1 xT-diff</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zalaegerszegi TE</td>
<td style="text-align: right;">1.145</td>
<td style="text-align: right;">38</td>
<td style="text-align: left;">keretérték (26-27) + xT-diff (25-26)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Honvéd</td>
<td style="text-align: right;">1.018</td>
<td style="text-align: right;">34</td>
<td style="text-align: left;">keretérték (26-27) — csak m1, nincs NB1 xT-diff</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Amit ez megmutat:</strong> egyetlen konzisztens modellcsalád fedi le mind a 12 csapatot — a visszatérőknél a kombinált (keretérték + xT-diff) modell, a feljutóknál ugyanennek a keretérték-tagja. Nincs többé patchwork (négy külön KPI-modell átlaga a visszatérőknek, bespoke kis mintás kalibráció a feljutóknak) — ez egyszerűbb, és minden eleme walk-forwarddal (vagy legalább nagy mintás visszateszteléssel) alátámasztott.</p>
<p><strong>Ez továbbra sem egy tökéletesen validált pontbecslés</strong> — N=30 (visszatérők) és N=48 (feljutók, az általános modellen keresztül) még mindig kis minta a futballelemzés léptékéhez képest, és a szezon közbeni tényezők (edzőváltás, sérülés, átigazolás) nincsenek benne. Inkább <strong>sáv-becslésként</strong>, mint éles pontrangsorként érdemes kezelni — a relatív sorrend (ki van elöl, ki hátul) megbízhatóbb, mint a pontos pontszám.</p>
</section>
</section>
<section id="gólmodell-a-poisson-szimulációhoz" class="level2">
<h2 class="anchored" data-anchor-id="gólmodell-a-poisson-szimulációhoz">Gólmodell a Poisson-szimulációhoz</h2>
<p>A fair oddsok (meccs-szintű 1X2, gólszám-alapú piacok) becsléséhez a pont/meccs-szintű power rankingnél finomabb bemenet kell: csapatonkénti <strong>támadóerő</strong> (várható lőtt gól/meccs) és <strong>védekező gyengeség</strong> (várható kapott gól/meccs) egy Poisson-alapú szimulációhoz. Ezeket ugyanolyan szisztematikus screeninggel és walk-forward validációval választottuk ki, mint a pontmodell prediktorait — nem magától értetődő, hogy ugyanaz a mutató (xT-diff) a legjobb erre is, hiszen a lőtt és a kapott gól két külön célváltozó, más-más mögöttes mechanizmussal.</p>
<section id="screening-mi-jósolja-legjobban-a-következő-szezon-lőttkapott-gólját" class="level3">
<h3 class="anchored" data-anchor-id="screening-mi-jósolja-legjobban-a-következő-szezon-lőttkapott-gólját">Screening: mi jósolja legjobban a következő szezon lőtt/kapott gólját</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Kandidansok szama: 78 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>=== TOP 6: lott gol (goals_next) ===</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  kpi                                                   n    r2   cor  rang
  &lt;chr&gt;                                             &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1 attackingtransition__xG within 10s after recovery    30 0.543 0.737     1
2 attack__xT                                           30 0.531 0.729     2
3 chancecreation__Box touches                          30 0.5   0.707     3
4 log_value_current                                    30 0.497 0.705     4
5 attack__Field tilt %                                 30 0.478 0.691     5
6 overallperformance__Field tilt %                     30 0.478 0.691     6</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
=== TOP 6: kapott gol (opp_goals_next) ===</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  kpi                                                    n    r2    cor  rang
  &lt;chr&gt;                                              &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;int&gt;
1 log_value_current                                     30 0.432 -0.657     1
2 chancecreation__Box touches                           30 0.364 -0.604     2
3 chancecreation__np Goals                              30 0.335 -0.579     3
4 attackingtransition__xT within 10s after recovery     30 0.31  -0.557     4
5 attackingtransition__Possessions retained after 5s    30 0.291 -0.539     5
6 attackingtransition__Recoveries                       30 0.288 -0.537     6</code></pre>
</div>
</div>
<p>Az <code>npxG</code> is szerepelt a screeningben, de nem az élen végzett: lőtt gólra a 78-ból a <strong>11.</strong> (R²=0.39), kapott gólra a <strong>8.</strong> (R²=0.275) — ugyanaz a mintázat, mint a pontmodellnél: az xG-alapú mutatók rendre gyengébben teljesítenek előrejelzésnél, mint a volumen-alapú (<code>Box touches</code>) vagy geometriai (<code>xT</code>) mutatók, valószínűleg mert az xG maga is zajos, modell-becsült mennyiség.</p>
</section>
<section id="walk-forward-validáció-és-a-végleges-választás" class="level3">
<h3 class="anchored" data-anchor-id="walk-forward-validáció-és-a-végleges-választás">Walk-forward validáció és a végleges választás</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Walk-forward OOS R² — lőtt gól jelöltek</caption>
<colgroup>
<col style="width: 53%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">prediktor</th>
<th style="text-align: right;">2023-24 -&gt; 2024-25</th>
<th style="text-align: right;">2024-25 -&gt; 2025-26</th>
<th style="text-align: right;">atlag</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">attackingtransition__xG within 10s after recovery</td>
<td style="text-align: right;">0.339</td>
<td style="text-align: right;">0.626</td>
<td style="text-align: right;">0.483</td>
</tr>
<tr class="even">
<td style="text-align: left;">attack__xT</td>
<td style="text-align: right;">0.455</td>
<td style="text-align: right;">0.266</td>
<td style="text-align: right;">0.361</td>
</tr>
<tr class="odd">
<td style="text-align: left;">chancecreation__Box touches</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">0.509</td>
<td style="text-align: right;">0.262</td>
</tr>
<tr class="even">
<td style="text-align: left;">log_value_current</td>
<td style="text-align: right;">0.097</td>
<td style="text-align: right;">0.344</td>
<td style="text-align: right;">0.220</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Walk-forward OOS R² — kapott gól jelöltek</caption>
<colgroup>
<col style="width: 52%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">prediktor</th>
<th style="text-align: right;">2023-24 -&gt; 2024-25</th>
<th style="text-align: right;">2024-25 -&gt; 2025-26</th>
<th style="text-align: right;">atlag</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">log_value_current</td>
<td style="text-align: right;">0.400</td>
<td style="text-align: right;">0.338</td>
<td style="text-align: right;">0.369</td>
</tr>
<tr class="even">
<td style="text-align: left;">chancecreation__Box touches</td>
<td style="text-align: right;">-0.258</td>
<td style="text-align: right;">0.451</td>
<td style="text-align: right;">0.096</td>
</tr>
<tr class="odd">
<td style="text-align: left;">chancecreation__np Goals</td>
<td style="text-align: right;">-0.664</td>
<td style="text-align: right;">0.246</td>
<td style="text-align: right;">-0.209</td>
</tr>
<tr class="even">
<td style="text-align: left;">attackingtransition__xT within 10s after recovery</td>
<td style="text-align: right;">0.072</td>
<td style="text-align: right;">0.329</td>
<td style="text-align: right;">0.200</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A legmagasabb screenelt szám (<code>xG within 10s after recovery</code>, átlag OOS R²=0.483) egy szűk, “egzotikus” mutató — 78 kandidánsból screenelve, N=30-on ez gyanús lehet véletlen csúcsra. Ugyanazt a logikát követve, mint a pontmodellnél (<code>Box touches</code> helyett <code>xT</code>-t választottuk, mert konceptuálisan egyszerűbb és nem a legmagasabb egyszeri screenelt szám hajszolása volt a cél): a <strong><code>xT</code>-t választjuk lőtt gólra</strong> (átlag OOS R²=0.361, konceptuálisan megegyezik a pontmodellben már bevált mutatóval), és a <strong>keretértéket kapott gólra</strong> (átlag OOS R²=0.369, egyértelműen a legstabilabb — minden más KPI-jelölt vagy instabil, vagy kifejezetten rossz ezen a célváltozón).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Golmodell (xT alapon), N=30:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept) 0.04554581  0.2670458 0.1705543 8.658007e-01
attack__xT  0.93807730  0.1664942 5.6342948 4.917728e-06</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Kapott golmodell (keretertek alapon), N=30:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                    Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept)        6.5896911 1.11683678  5.900317 2.393812e-06
log_value_current -0.4035078 0.08746027 -4.613612 7.971738e-05</code></pre>
</div>
</div>
</section>
<section id="várható-lőttkapott-gól-csapatonként" class="level3">
<h3 class="anchored" data-anchor-id="várható-lőttkapott-gól-csapatonként">2026-27 várható lőtt/kapott gól csapatonként</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>26/27 várható lőtt/kapott gól csapatonként — Poisson-szimuláció alapja</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 17%">
<col style="width: 18%">
<col style="width: 14%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">team</th>
<th style="text-align: right;">Várható lőtt gól/meccs</th>
<th style="text-align: right;">Várható kapott gól/meccs</th>
<th style="text-align: right;">Gólkülönbség/meccs</th>
<th style="text-align: left;">Forrás</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ferencváros</td>
<td style="text-align: right;">1.687</td>
<td style="text-align: right;">0.992</td>
<td style="text-align: right;">0.696</td>
<td style="text-align: left;">xT (25-26) / keretérték (26-27)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Győri ETO</td>
<td style="text-align: right;">1.950</td>
<td style="text-align: right;">1.305</td>
<td style="text-align: right;">0.644</td>
<td style="text-align: left;">xT (25-26) / keretérték (26-27)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Paksi FC</td>
<td style="text-align: right;">1.950</td>
<td style="text-align: right;">1.545</td>
<td style="text-align: right;">0.405</td>
<td style="text-align: left;">xT (25-26) / keretérték (26-27)</td>
</tr>
<tr class="even">
<td style="text-align: left;">MTK</td>
<td style="text-align: right;">1.471</td>
<td style="text-align: right;">1.372</td>
<td style="text-align: right;">0.100</td>
<td style="text-align: left;">xT (25-26) / keretérték (26-27)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Puskás FC</td>
<td style="text-align: right;">1.490</td>
<td style="text-align: right;">1.408</td>
<td style="text-align: right;">0.083</td>
<td style="text-align: left;">xT (25-26) / keretérték (26-27)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Újpest</td>
<td style="text-align: right;">1.349</td>
<td style="text-align: right;">1.345</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: left;">xT (25-26) / keretérték (26-27)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Debrecen</td>
<td style="text-align: right;">1.387</td>
<td style="text-align: right;">1.522</td>
<td style="text-align: right;">-0.135</td>
<td style="text-align: left;">xT (25-26) / keretérték (26-27)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nyíregyháza Spartacus</td>
<td style="text-align: right;">1.256</td>
<td style="text-align: right;">1.579</td>
<td style="text-align: right;">-0.324</td>
<td style="text-align: left;">xT (25-26) / keretérték (26-27)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Vasas</td>
<td style="text-align: right;">1.296</td>
<td style="text-align: right;">1.639</td>
<td style="text-align: right;">-0.343</td>
<td style="text-align: left;">keretérték (26-27) — csak m1-szerű fallback</td>
</tr>
<tr class="even">
<td style="text-align: left;">Várda SE</td>
<td style="text-align: right;">1.199</td>
<td style="text-align: right;">1.583</td>
<td style="text-align: right;">-0.383</td>
<td style="text-align: left;">xT (25-26) / keretérték (26-27)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zalaegerszegi TE</td>
<td style="text-align: right;">1.274</td>
<td style="text-align: right;">1.671</td>
<td style="text-align: right;">-0.396</td>
<td style="text-align: left;">xT (25-26) / keretérték (26-27)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Honvéd</td>
<td style="text-align: right;">1.181</td>
<td style="text-align: right;">1.737</td>
<td style="text-align: right;">-0.556</td>
<td style="text-align: left;">keretérték (26-27) — csak m1-szerű fallback</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Ez a táblázat adja a Poisson-szimuláció bemenetét: minden csapatnak van egy várható lőtt és kapott gól/meccs értéke.</p>
<p><strong>Korlát</strong>: ugyanaz az N=30, 2 tesztpontos walk-forward érvényes itt is, mint a pontmodellnél — ez egy első, védhető közelítés, nem egy véglegesen kalibrált gólmodell.</p>
</section>
<section id="attackdefense-rating-és-a-mérkőzés-szintű-lambda" class="level3">
<h3 class="anchored" data-anchor-id="attackdefense-rating-és-a-mérkőzés-szintű-lambda">Attack/defense rating és a mérkőzés-szintű lambda</h3>
<p>A csapatonkénti várható lőtt/kapott gólt (átlagos ellenféllel szemben) <strong>relatív attack/defense ratinggé</strong> alakítjuk (1,0 = liga-átlag), majd egy adott párosításra a klasszikus (Maher/Dixon-Coles-stílusú) szorzatos formával kombináljuk, a hazai pálya előnnyel (ld. fent, +0,112 gól/meccs a nyers adatból számolva) együtt:</p>
<p><span class="math display">\[
\lambda_{\text{hazai}} = \bar{g} \cdot \text{attack}_{\text{hazai}} \cdot \text{defense}_{\text{vendég}} \cdot f_{\text{hazai}}, \quad
\lambda_{\text{vendég}} = \bar{g} \cdot \text{attack}_{\text{vendég}} \cdot \text{defense}_{\text{hazai}} \cdot f_{\text{vendég}}
\]</span></p>
<p>ahol <span class="math inline">\(\bar{g}\)</span> a liga-átlag gól/meccs, <span class="math inline">\(f_{\text{hazai}}\)</span>/<span class="math inline">\(f_{\text{vendég}}\)</span> pedig a 2025-26-os tényleges hazai/vendég gólátlagból számolt szorzó.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Liga-atlag gol/meccs: 1.508 | Hazai szorzo: 1.037 | Vendeg szorzo: 0.963 </code></pre>
</div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>26/27 attack/defense rating (1,0 = liga-átlag)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">team</th>
<th style="text-align: right;">attack</th>
<th style="text-align: right;">defense</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Győri ETO</td>
<td style="text-align: right;">1.293</td>
<td style="text-align: right;">0.866</td>
</tr>
<tr class="even">
<td style="text-align: left;">Paksi FC</td>
<td style="text-align: right;">1.293</td>
<td style="text-align: right;">1.025</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ferencváros</td>
<td style="text-align: right;">1.119</td>
<td style="text-align: right;">0.658</td>
</tr>
<tr class="even">
<td style="text-align: left;">Puskás FC</td>
<td style="text-align: right;">0.988</td>
<td style="text-align: right;">0.934</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MTK</td>
<td style="text-align: right;">0.976</td>
<td style="text-align: right;">0.910</td>
</tr>
<tr class="even">
<td style="text-align: left;">Debrecen</td>
<td style="text-align: right;">0.920</td>
<td style="text-align: right;">1.009</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Újpest</td>
<td style="text-align: right;">0.895</td>
<td style="text-align: right;">0.892</td>
</tr>
<tr class="even">
<td style="text-align: left;">Vasas</td>
<td style="text-align: right;">0.860</td>
<td style="text-align: right;">1.087</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zalaegerszegi TE</td>
<td style="text-align: right;">0.845</td>
<td style="text-align: right;">1.108</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nyíregyháza Spartacus</td>
<td style="text-align: right;">0.833</td>
<td style="text-align: right;">1.048</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Várda SE</td>
<td style="text-align: right;">0.796</td>
<td style="text-align: right;">1.050</td>
</tr>
<tr class="even">
<td style="text-align: left;">Honvéd</td>
<td style="text-align: right;">0.783</td>
<td style="text-align: right;">1.152</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="dixon-coles-alacsony-gólszámú-korrekció-saját-adatból-illesztve" class="level3">
<h3 class="anchored" data-anchor-id="dixon-coles-alacsony-gólszámú-korrekció-saját-adatból-illesztve">Dixon-Coles alacsony-gólszámú korrekció, saját adatból illesztve</h3>
<p>A tiszta függetlenségi feltevés (Poisson(λ_hazai) × Poisson(λ_vendég)) alábecsüli a döntetlenek gyakoriságát alacsony gólszámoknál — ez jól dokumentált jelenség (Dixon-Coles, 1997). A korrekciós paramétert (ρ) <strong>nem külföldi ligából vett irodalmi értékkel</strong> vesszük át, hanem a saját 2025-26-os, 197 tényleges NB1-meccsünkre illesztjük: egy in-season Poisson-GLM-mel (<code>goals ~ hazai/vendég + csapat + ellenfél</code>) minden meccsre kiszámoljuk a tényleges λ-kat, majd ρ-t maximum likelihood-dal illesztjük az alacsony-gólszámú korrekciós függvényre.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Illesztett Dixon-Coles rho: -0.0357 
(az irodalomban jellemzően -0.1 és -0.2 között — a miénk gyengébb, valószínűleg a kis mintánk miatt)</code></pre>
</div>
</div>
</section>
<section id="fair-oddsok-az-első-fordulóra" class="level3">
<h3 class="anchored" data-anchor-id="fair-oddsok-az-első-fordulóra">Fair oddsok az első fordulóra</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Első forduló — Dixon-Coles Poisson fair oddsok (1X2, Over 2.5, mindkét csapat szerez gólt)</caption>
<colgroup>
<col style="width: 32%">
<col style="width: 25%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 13%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">home</th>
<th style="text-align: left;">away</th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">X</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">Over 2.5</th>
<th style="text-align: right;">BTTS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Nyíregyháza Spartacus</td>
<td style="text-align: left;">Újpest</td>
<td style="text-align: right;">3.17</td>
<td style="text-align: right;">3.62</td>
<td style="text-align: right;">2.44</td>
<td style="text-align: right;">2.16</td>
<td style="text-align: right;">1.94</td>
</tr>
<tr class="even">
<td style="text-align: left;">Várda SE</td>
<td style="text-align: left;">Honvéd</td>
<td style="text-align: right;">2.38</td>
<td style="text-align: right;">3.72</td>
<td style="text-align: right;">3.23</td>
<td style="text-align: right;">2.05</td>
<td style="text-align: right;">1.87</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Vasas</td>
<td style="text-align: left;">Győri ETO</td>
<td style="text-align: right;">4.78</td>
<td style="text-align: right;">4.57</td>
<td style="text-align: right;">1.75</td>
<td style="text-align: right;">1.61</td>
<td style="text-align: right;">1.66</td>
</tr>
<tr class="even">
<td style="text-align: left;">Debrecen</td>
<td style="text-align: left;">Puskás FC</td>
<td style="text-align: right;">2.90</td>
<td style="text-align: right;">3.83</td>
<td style="text-align: right;">2.54</td>
<td style="text-align: right;">1.89</td>
<td style="text-align: right;">1.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Paksi FC</td>
<td style="text-align: left;">Ferencváros</td>
<td style="text-align: right;">3.30</td>
<td style="text-align: right;">4.03</td>
<td style="text-align: right;">2.22</td>
<td style="text-align: right;">1.74</td>
<td style="text-align: right;">1.67</td>
</tr>
<tr class="even">
<td style="text-align: left;">MTK</td>
<td style="text-align: left;">Zalaegerszegi TE</td>
<td style="text-align: right;">1.98</td>
<td style="text-align: right;">4.02</td>
<td style="text-align: right;">4.05</td>
<td style="text-align: right;">1.88</td>
<td style="text-align: right;">1.81</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Összevetés a korábbi, egyszerűbb multinomiális logit-modellel</strong>: a két megközelítés a legtöbb meccsen közel áll egymáshoz (pl. Nyíregyháza–Újpest: 3,16 vs.&nbsp;3,17 hazai odds), de két helyen érdemben eltér — a <strong>Vasas–Győri ETO</strong> és a <strong>Paksi FC–Ferencváros</strong> meccseken a Poisson-modell <strong>jóval kisebb esélytelenséget</strong> ad a gyengébb hazai csapatnak (pl. Paksi FC–Ferencváros: multinomiális 4,92 vs.&nbsp;Poisson 3,30 a hazai győzelemre). Ennek oka, hogy a két modell más-más adatforrásból építkezik: a multinomiális logit a pont/meccs-különbségre van kalibrálva, a Poisson-modell viszont külön becsli a támadást és a védekezést — ha egy csapat (mint Paksi FC) jó támadó, de gyengébb védekező ratinggel rendelkezik, a Poisson-modell ezt finomabban tudja kezelni, mint az egydimenziós “erősségkülönbség”.</p>
</section>
<section id="ázsiai-hendikep-ah-az-első-fordulóra" class="level3">
<h3 class="anchored" data-anchor-id="ázsiai-hendikep-ah-az-első-fordulóra">Ázsiai hendikep (AH) az első fordulóra</h3>
<p>A teljes eredmény-valószínűségi mátrixból (a fenti Dixon-Coles-korrigált Poisson-rács) bármilyen hendikep-vonalra levezethető a fair odds — nem csak a szokásos 1X2-re. A negyedes vonalakat (pl. ±0,25, ±0,75) a két szomszédos fél/egész vonal (pl. 0 és -0,5) 50-50%-os feltétes tétjeként kezeljük, ahogy a valódi ázsiai hendikep-fogadóirodák is teszik: a becsült profit/veszteség várható értékét nullázó (fair) odds-ot számoljuk ki minden vonalra, majd kiválasztjuk a <strong>fő vonalat</strong> (ahol a hazai csapat “cover” valószínűsége a legközelebb esik 50%-hoz).</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Első forduló — ázsiai hendikep fő vonal és fair odds</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">home</th>
<th style="text-align: left;">away</th>
<th style="text-align: right;">Fő vonal (hazai)</th>
<th style="text-align: right;">Odds (hazai)</th>
<th style="text-align: right;">Odds (vendég)</th>
<th style="text-align: right;">Hazai cover-valószínűség</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Nyíregyháza Spartacus</td>
<td style="text-align: left;">Újpest</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">1.90</td>
<td style="text-align: right;">2.11</td>
<td style="text-align: right;">0.525</td>
</tr>
<tr class="even">
<td style="text-align: left;">Várda SE</td>
<td style="text-align: left;">Honvéd</td>
<td style="text-align: right;">-0.25</td>
<td style="text-align: right;">2.05</td>
<td style="text-align: right;">1.95</td>
<td style="text-align: right;">0.487</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Vasas</td>
<td style="text-align: left;">Győri ETO</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">2.08</td>
<td style="text-align: right;">1.93</td>
<td style="text-align: right;">0.482</td>
</tr>
<tr class="even">
<td style="text-align: left;">Debrecen</td>
<td style="text-align: left;">Puskás FC</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">2.14</td>
<td style="text-align: right;">1.88</td>
<td style="text-align: right;">0.468</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Paksi FC</td>
<td style="text-align: left;">Ferencváros</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">2.05</td>
<td style="text-align: right;">1.95</td>
<td style="text-align: right;">0.487</td>
</tr>
<tr class="even">
<td style="text-align: left;">MTK</td>
<td style="text-align: left;">Zalaegerszegi TE</td>
<td style="text-align: right;">-0.50</td>
<td style="text-align: right;">1.98</td>
<td style="text-align: right;">2.02</td>
<td style="text-align: right;">0.504</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Korlátok, amik a Poisson-modellre specifikusan vonatkoznak:</strong></p>
<ol type="1">
<li>A ρ paraméter egyetlen szezon 197 meccsén lett illesztve — ez a legkisebb, legbizonytalanabb becslésünk az egész dokumentumban.</li>
<li>A hazai pálya előny egységes minden csapatra (ld. korábbi megbeszélés — csapat-specifikus hazai előnyt nem tudtunk stabilan megbecsülni).</li>
<li>Az attack/defense rating maga a már bemutatott xT-/keretérték-alapú gólmodellből jön, tehát annak minden korlátja (N=30, 2 tesztpont) örökeresztül száll ide is.</li>
<li>Nincs benne szezon közbeni forma, sérülés, átigazolás — ugyanaz a korlát, mint a pontmodellnél.</li>
</ol>
</section>
</section>
<section id="ismert-korlátok" class="level2">
<h2 class="anchored" data-anchor-id="ismert-korlátok">Ismert korlátok</h2>
<ol type="1">
<li><strong>A 48 sor nem 48 független megfigyelés</strong> — ugyanazok a csapatok évről évre visszatérnek, a keretértékük/erejük autokorrelált. Ez a modell OLS p-értékét (p &lt; 0.0001) technikailag túl magabiztossá teszi (a standard hiba klaszterezés nélkül alábecsült), <strong>de ez a gyakorlatban nem érinti az over/under sávot</strong>: azt már amúgy is a walk-forward empirikus RMSE-ből építjük, nem az OLS-standardhibából — és mivel 2026-27-ben is túlnyomórészt ugyanezek a csapatok játszanak, a walk-forward validáció pontosan a releváns helyzetet méri (visszatérő csapat jövőbeli szezonjának jóslása). Ahol ez a nem-függetlenség ténylegesen számít: egy <strong>teljesen új, korábban sosem látott feljutó csapatnál</strong>, ahol a modellnek a populációs szintű összefüggésre kell hagyatkoznia, nincs mit “megismételni” a csapat korábbi szezonjaiból.</li>
<li><strong>Nincs edző/taktikai infó, sérülésadat, szezon közbeni átigazolás</strong> — ezek mind a reziduálisban landolnak.</li>
<li><strong>A keretérték időzítése</strong> a historikus szezonokra nem egzakt dátumú (ld. fent) — ez rendben van a visszatesztelésnél, de a friss predikciónál a scrape időzítését gondosan kell megválasztani.</li>
<li><strong>A feljutó-hatás (n=4-6) nem megbízhatóan becsülhető külön modellként</strong> ebből a mintából — ezért is döntöttünk úgy, hogy a feljutókra nem bespoke kalibrációt, hanem a nagy mintás (N=48) általános keretérték-modellt (<code>m1</code>) használjuk, ld. “Végleges modell” szakasz.</li>
<li><strong>NB2-es keretérték hiánya</strong> — jelenleg csak az NB1-ben töltött szezonokra van adatunk; ha egy csapat NB2-ben van, nincs “előző NB1-es szezon” adata a modellhez. A feljutók NB2-es búcsúszezonja (végeredmény szintjén) megvan (<code>futball/data/nb2_promoted_teams_history.csv</code>), de ez csak leíró kontextusként szerepel, nem hajt önálló számot (ld. fent, miért).</li>
<li><strong>A visszatérőkre használt kombinált modell (keretérték + xT-diff) és az önálló xT-diff-modell teljesítménye N=30-on statisztikailag nem különíthető el</strong> — a választás konceptuális indoklású (két független infoforrás), nem bizonyítottan jobb teljesítményű.</li>
</ol>
</section>
<section id="következő-lépések" class="level2">
<h2 class="anchored" data-anchor-id="következő-lépések">Következő lépések</h2>
<ul>
<li><del>Friss 2026-27-es keretérték-scrape a szezonkezdéshez időzítve</del> — <strong>kész</strong>, ld. “Végleges egyesített 2026-27 tábla”.</li>
<li><del>A négy szezon predikciójának összevetése a modellel — konkrét over/under táblázat a 2026-27-es szezonra</del> — <strong>kész</strong>.</li>
<li><del>Feljutók kezelése</del> — <strong>kész</strong>: a bespoke N=6-os NB2-kalibráció helyett a nagy mintás keretérték-modellt (<code>m1</code>) alkalmazzuk rájuk is, az NB2-es végeredmény leíró kontextusként marad.</li>
<li><del>Box touches vs.&nbsp;xT-diff vs.&nbsp;xG-diff valódi walk-forward összevetése</del> — <strong>kész</strong>, kiderült, hogy a korábbi “Box touches nyer” következtetés téves volt (stabilitást kevert össze előrejelző erővel); az xT-diff a jobb prediktor.</li>
<li>Opcionális, jövőbeli bővítés: NB2-es KPI-adatok (pl. xT-diff) bevonása a feljutók becslésébe, ha több NB2-szezonra visszamenőleg összegyűlik a <code>team_stats</code> — ekkor érdemes újra megnézni, ad-e hozzá bármit a keretérték-modellhez.</li>
<li>A szezon előrehaladtával érdemes frissíteni/visszatesztelni az előrejelzést a tényleges eredmények ellenében — ez adja majd a 3. valódi walk-forward tesztpontot is.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">Levente Kaszai — Hungarian Sports Analytics</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>