<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-04-20">
<meta name="description" content="A wDRE* mutató felépítése: Bayesian shrinkage, korrekciók és az értékelési logika.">

<title>Levente Kaszai - wDRE* — Módszertani dokumentáció</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&amp;display=swap" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Levente Kaszai</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./archivum.html" rel="" target="">
 <span class="menu-text">Archívum</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-kosárlabda" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Kosárlabda</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-kosárlabda">    
        <li>
    <a class="dropdown-item" href="./four_factors_1.html" rel="" target="">
 <span class="dropdown-text">Four Factors</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./scoring_efficiency.html" rel="" target="">
 <span class="dropdown-text">Scoring Efficiency</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./pace_efficiency.html" rel="" target="">
 <span class="dropdown-text">Játékritmus &amp; Hatékonyság</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analytics.html" rel="" target="">
 <span class="dropdown-text">🔒 Analytics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./advanced_metrics.html" rel="" target="">
 <span class="dropdown-text">Advanced Metrics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./wdre_metodologia.html" rel="" target="">
 <span class="dropdown-text">wDRE* Módszertan</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./player_ratings.html" rel="" target="">
 <span class="dropdown-text">Játékosértékelés</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./jatekosok.html" rel="" target="">
 <span class="dropdown-text">Játékos profilok</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labdarúgás" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Labdarúgás</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labdarúgás">    
        <li>
    <a class="dropdown-item" href="./futball/analytics.html" rel="" target="">
 <span class="dropdown-text">🔒 Analytics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./futball/striker_clustering.html" rel="" target="">
 <span class="dropdown-text">Csatár klaszterezés</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./futball/player_ratings.html" rel="" target="">
 <span class="dropdown-text">Játékosértékelés</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./futball/jatekosok.html" rel="" target="">
 <span class="dropdown-text">Játékos profilok</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/leventekaszai" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tartalom</h2>
   
  <ul>
  <li><a href="#áttekintés" id="toc-áttekintés" class="nav-link active" data-scroll-target="#áttekintés">Áttekintés</a></li>
  <li><a href="#az-alap-dre" id="toc-az-alap-dre" class="nav-link" data-scroll-target="#az-alap-dre">1. Az alap: DRE</a>
  <ul class="collapse">
  <li><a href="#eredet" id="toc-eredet" class="nav-link" data-scroll-target="#eredet">1.1 Eredet</a></li>
  <li><a href="#formula" id="toc-formula" class="nav-link" data-scroll-target="#formula">1.2 Formula</a></li>
  <li><a href="#validáció-az-nb1-en" id="toc-validáció-az-nb1-en" class="nav-link" data-scroll-target="#validáció-az-nb1-en">1.3 Validáció az NB1-en</a></li>
  </ul></li>
  <li><a href="#bayesian-shrinkage" id="toc-bayesian-shrinkage" class="nav-link" data-scroll-target="#bayesian-shrinkage">2. Bayesian shrinkage</a>
  <ul class="collapse">
  <li><a href="#probléma" id="toc-probléma" class="nav-link" data-scroll-target="#probléma">2.1 Probléma</a></li>
  <li><a href="#formula-1" id="toc-formula-1" class="nav-link" data-scroll-target="#formula-1">2.2 Formula</a></li>
  <li><a href="#k-értékek-empirikus-levezetése" id="toc-k-értékek-empirikus-levezetése" class="nav-link" data-scroll-target="#k-értékek-empirikus-levezetése">2.3 k-értékek empirikus levezetése</a></li>
  </ul></li>
  <li><a href="#decay-súlyozás" id="toc-decay-súlyozás" class="nav-link" data-scroll-target="#decay-súlyozás">3. Decay-súlyozás</a>
  <ul class="collapse">
  <li><a href="#motiváció" id="toc-motiváció" class="nav-link" data-scroll-target="#motiváció">3.1 Motiváció</a></li>
  <li><a href="#empirikus-megállapítás-β-nem-azonosítható-4-szezonból" id="toc-empirikus-megállapítás-β-nem-azonosítható-4-szezonból" class="nav-link" data-scroll-target="#empirikus-megállapítás-β-nem-azonosítható-4-szezonból">3.2 Empirikus megállapítás: β nem azonosítható 4 szezonból</a></li>
  </ul></li>
  <li><a href="#életkori-kiigazítás-aging-curve" id="toc-életkori-kiigazítás-aging-curve" class="nav-link" data-scroll-target="#életkori-kiigazítás-aging-curve">4. Életkori kiigazítás (Aging Curve)</a>
  <ul class="collapse">
  <li><a href="#módszer" id="toc-módszer" class="nav-link" data-scroll-target="#módszer">4.1 Módszer</a></li>
  <li><a href="#értelmezés-és-korlátok" id="toc-értelmezés-és-korlátok" class="nav-link" data-scroll-target="#értelmezés-és-korlátok">4.2 Értelmezés és korlátok</a></li>
  <li><a href="#alkalmazás-a-modellben" id="toc-alkalmazás-a-modellben" class="nav-link" data-scroll-target="#alkalmazás-a-modellben">4.3 Alkalmazás a modellben</a></li>
  </ul></li>
  <li><a href="#a-teljes-wdre-pipeline" id="toc-a-teljes-wdre-pipeline" class="nav-link" data-scroll-target="#a-teljes-wdre-pipeline">5. A teljes wDRE* pipeline</a></li>
  <li><a href="#korlátok-és-jövőbeli-fejlesztések" id="toc-korlátok-és-jövőbeli-fejlesztések" class="nav-link" data-scroll-target="#korlátok-és-jövőbeli-fejlesztések">6. Korlátok és jövőbeli fejlesztések</a>
  <ul class="collapse">
  <li><a href="#jelenlegi-korlátok" id="toc-jelenlegi-korlátok" class="nav-link" data-scroll-target="#jelenlegi-korlátok">Jelenlegi korlátok</a></li>
  <li><a href="#tervezett-fejlesztések" id="toc-tervezett-fejlesztések" class="nav-link" data-scroll-target="#tervezett-fejlesztések">Tervezett fejlesztések</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">wDRE* — Módszertani dokumentáció</h1>
<p class="subtitle lead">Weighted, Bayesian-shrunk, age-adjusted Daily RAPM Estimate</p>
</div>

<div>
  <div class="description">
    A wDRE* mutató felépítése: Bayesian shrinkage, korrekciók és az értékelési logika.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 20, 2026</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="áttekintés" class="level2">
<h2 class="anchored" data-anchor-id="áttekintés">Áttekintés</h2>
<p>A <strong>wDRE*</strong> (Weighted, age-adjusted Daily RAPM Estimate) egy több szezonon alapuló játékosértékelő metrika, amely az NB1 2022–23 és 2025–26 közötti négy szezonjának box-score adatait használja. A módszertan három egymásra épülő lépésből áll:</p>
<ol type="1">
<li><strong>DRE</strong> — szezonon belüli RAPM-becslés box-score adatból, Bayesian shrinkage-gel</li>
<li><strong>wDRE</strong> — szezonsúlyozott karrierátlag exponenciális decay-vel</li>
<li><strong>wDRE*</strong> — életkori kiigazítással korrigált végső metrika</li>
</ol>
<p>A modell paramétereinek egy részét empirikusan, az NB1 adataiból vezettük le; ahol az adatmennyiség ezt nem tette lehetővé, ott az elméleti indoklást és a korlátokat is jelezzük.</p>
<hr>
</section>
<section id="az-alap-dre" class="level2">
<h2 class="anchored" data-anchor-id="az-alap-dre">1. Az alap: DRE</h2>
<section id="eredet" class="level3">
<h3 class="anchored" data-anchor-id="eredet">1.1 Eredet</h3>
<p>A DRE (Daily RAPM Estimate) Ryan Myers 2017-es munkáján alapul. Az eredeti célja az NBA-ban mért RAPM (Regularized Adjusted Plus-Minus) közelítése kizárólag box-score adatokból, lineáris regresszión keresztül. A formula együtthatói NBA-szintű RAPM-adatokra illesztett OLS-regresszióból származnak.</p>
</section>
<section id="formula" class="level3">
<h3 class="anchored" data-anchor-id="formula">1.2 Formula</h3>
<p>A szezonon belüli nyers DRE:</p>
<p><span class="math display">\[
\text{DRE} = -8.424 + 0.792\cdot\text{PTS}_{100} - 0.719\cdot\text{2PA}_{100} - 0.552\cdot\text{3PA}_{100}
\]</span> <span class="math display">\[
- 0.159\cdot\text{FTA}_{100} + 0.135\cdot\text{ORB}_{100} + 0.400\cdot\text{DRB}_{100} + 0.544\cdot\text{AST}_{100}
\]</span> <span class="math display">\[
+ 1.680\cdot\text{STL}_{100} + 0.764\cdot\text{BLK}_{100} - 1.360\cdot\text{TOV}_{100} - 0.108\cdot\text{PF}_{100}
\]</span></p>
<p>Ahol minden stat 100 csapatbirtoklásra normalizált. Az STL/100 speciálisan számított:</p>
<p><span class="math display">\[
\text{STL}_{100} = \text{STL}_{\text{raw}} \times \frac{\text{TOV}_{100}}{\text{TOV}_{\text{raw}}}
\]</span></p>
<p><strong>Mértékegység:</strong> a 0 a ligaátlagot jelenti, +5 körülbelül All-Star szintnek felel meg NBA-ban. Az NB1 esetén a skála hasonló, de az abszolút értékek nem közvetlenül összehasonlíthatók NBA-metrikákkal.</p>
</section>
<section id="validáció-az-nb1-en" class="level3">
<h3 class="anchored" data-anchor-id="validáció-az-nb1-en">1.3 Validáció az NB1-en</h3>
<p>Az alábbi teszt megmutatja, hogy a DRE és a BPM (Box Plus/Minus) közül melyik közelíti jobban az NB1 valóságát:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>DRE vs BPM validáció — NB1 2022–2026 (min. 200 perc)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Teszt</th>
<th style="text-align: center;">BPM R²</th>
<th style="text-align: center;">DRE R²</th>
<th style="text-align: left;">Győztes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Csapat Gy% korreláció</td>
<td style="text-align: center;">0.760</td>
<td style="text-align: center;">0.738</td>
<td style="text-align: left;">BPM</td>
</tr>
<tr class="even">
<td style="text-align: left;">On-off Net RTG korreláció</td>
<td style="text-align: center;">0.199</td>
<td style="text-align: center;">0.215</td>
<td style="text-align: left;">DRE ✓</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Év-év stabilitás (R²)</td>
<td style="text-align: center;">0.464</td>
<td style="text-align: center;">0.512</td>
<td style="text-align: left;">DRE ✓</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A DRE 2–1-re győz. A BPM csapat Gy%-ban mutatott előnye részben annak köszönhető, hogy az ORtg — amely közvetlen bemenete — erősen korrelál a győzelemmel, ez azonban egy részbeni körforgást okoz. Az on-off Net RTG ezzel szemben <strong>független mérés</strong>, ezért a legmegbízhatóbb benchmark.</p>
<hr>
</section>
</section>
<section id="bayesian-shrinkage" class="level2">
<h2 class="anchored" data-anchor-id="bayesian-shrinkage">2. Bayesian shrinkage</h2>
<section id="probléma" class="level3">
<h3 class="anchored" data-anchor-id="probléma">2.1 Probléma</h3>
<p>Kis mintánál (kevés perc) a nyers DRE-komponensek torzítottak: egy 100 perces játékos 3P%-a nem megbízható. Bayesian regresszióval a megfigyelést a ligaátlag felé húzzuk, az együttsúlya a mintamérettől függ.</p>
</section>
<section id="formula-1" class="level3">
<h3 class="anchored" data-anchor-id="formula-1">2.2 Formula</h3>
<p>Minden DRE-komponensre külön:</p>
<p><span class="math display">\[
\hat{x}_i = \frac{\text{Min}_i \cdot x_i + k \cdot \bar{x}_{\text{liga}}}{\text{Min}_i + k}
\]</span></p>
<p>Ahol:</p>
<ul>
<li><span class="math inline">\(x_i\)</span> — a játékos megfigyelt statisztikája</li>
<li><span class="math inline">\(\bar{x}_{\text{liga}}\)</span> — a szezon ligaátlaga (200+ perces játékosok)</li>
<li><span class="math inline">\(k\)</span> — shrinkage paraméter (percben mérve)</li>
<li><span class="math inline">\(\text{Min}_i\)</span> — a játékos percei</li>
</ul>
</section>
<section id="k-értékek-empirikus-levezetése" class="level3">
<h3 class="anchored" data-anchor-id="k-értékek-empirikus-levezetése">2.3 k-értékek empirikus levezetése</h3>
<p>A k-értékeket <strong>ICC (Intraclass Correlation Coefficient)</strong> alapján vezettük le az NB1 adataiból (2022–2026, 200+ perces játékosok, legalább 2 szezon):</p>
<p><span class="math display">\[
\text{ICC} = \frac{\sigma^2_{\text{tehetség}}}{\sigma^2_{\text{tehetség}} + \sigma^2_{\text{hiba}}}
\qquad
k = \frac{1 - \text{ICC}}{\text{ICC}} \times \bar{\text{Min}}_{\text{szn}}
\]</span></p>
<p>Ahol <span class="math inline">\(\bar{\text{Min}}_{\text{szn}} \approx 604\)</span> perc (NB1 átlag, 200+ min játékosok).</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Empirikus k-értékek — NB1 ICC-alapú variancia-dekompozíció</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Stat</th>
<th style="text-align: center;">ICC</th>
<th style="text-align: center;">k (perc)</th>
<th style="text-align: center;">Stabilitás</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PTS/100</td>
<td style="text-align: center;">0.829</td>
<td style="text-align: center;">125</td>
<td style="text-align: center;">Nagyon stabil</td>
</tr>
<tr class="even">
<td style="text-align: left;">2PA/100</td>
<td style="text-align: center;">0.850</td>
<td style="text-align: center;">110</td>
<td style="text-align: center;">Nagyon stabil</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3PA/100</td>
<td style="text-align: center;">0.870</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">Nagyon stabil</td>
</tr>
<tr class="even">
<td style="text-align: left;">FTA/100</td>
<td style="text-align: center;">0.741</td>
<td style="text-align: center;">210</td>
<td style="text-align: center;">Stabil</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ORB/100</td>
<td style="text-align: center;">0.822</td>
<td style="text-align: center;">130</td>
<td style="text-align: center;">Nagyon stabil</td>
</tr>
<tr class="even">
<td style="text-align: left;">DRB/100</td>
<td style="text-align: center;">0.792</td>
<td style="text-align: center;">160</td>
<td style="text-align: center;">Stabil</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AST/100</td>
<td style="text-align: center;">0.864</td>
<td style="text-align: center;">95</td>
<td style="text-align: center;">Nagyon stabil</td>
</tr>
<tr class="even">
<td style="text-align: left;">STL/100</td>
<td style="text-align: center;">0.454</td>
<td style="text-align: center;">730</td>
<td style="text-align: center;">Leginstabilabb</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BLK/100</td>
<td style="text-align: center;">0.694</td>
<td style="text-align: center;">265</td>
<td style="text-align: center;">Közepes</td>
</tr>
<tr class="even">
<td style="text-align: left;">TOV/100</td>
<td style="text-align: center;">0.680</td>
<td style="text-align: center;">285</td>
<td style="text-align: center;">Közepes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PF/100</td>
<td style="text-align: center;">0.793</td>
<td style="text-align: center;">160</td>
<td style="text-align: center;">Stabil</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Főbb tanulság:</strong> Az NB1 statisztikák általában <strong>rendkívül stabilak</strong> szezonok között (ICC 0.45–0.87), ami azt jelenti, hogy kevés shrinkage szükséges. Az egyetlen kivétel a STL/100 (ICC=0.454), ahol a legnagyobb a véletlen játéka — ez konzisztens az NBA-szintű stabilitás-kutatásokkal (Krishna Narsu, 2015).</p>
<hr>
</section>
</section>
<section id="decay-súlyozás" class="level2">
<h2 class="anchored" data-anchor-id="decay-súlyozás">3. Decay-súlyozás</h2>
<section id="motiváció" class="level3">
<h3 class="anchored" data-anchor-id="motiváció">3.1 Motiváció</h3>
<p>Egy játékos 3 évvel ezelőtti teljesítménye kevésbé releváns a jelenlegi értékeléshez, mint a legutóbbi szezoné. Az exponenciális decay ezt formalizálja:</p>
<p><span class="math display">\[
w_t = \beta^{\,\Delta t}
\]</span></p>
<p>Ahol <span class="math inline">\(\Delta t\)</span> az évek száma a legfrissebb szezonhoz képest, <span class="math inline">\(\beta \in (0, 1)\)</span>.</p>
</section>
<section id="empirikus-megállapítás-β-nem-azonosítható-4-szezonból" class="level3">
<h3 class="anchored" data-anchor-id="empirikus-megállapítás-β-nem-azonosítható-4-szezonból">3.2 Empirikus megállapítás: β nem azonosítható 4 szezonból</h3>
<p>A <span class="math inline">\(\beta\)</span> optimalizálásához minden egymást követő szezonpáron (N→N+1) kereszt-validáltuk a súlyozott múlt-DRE → következő szezon korrelációt:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Cross-validáció eredménye: β nem befolyásolja a prediktív erőt</caption>
<thead>
<tr class="header">
<th style="text-align: center;">β</th>
<th style="text-align: center;">R²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">0.5128</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.35</td>
<td style="text-align: center;">0.5128</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">0.5128</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.65</td>
<td style="text-align: center;">0.5128</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.80</td>
<td style="text-align: center;">0.5128</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.95</td>
<td style="text-align: center;">0.5128</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Az eredmény: <strong>minden β értéknél azonos R² = 0.5128</strong>. Ez nem hibát jelez, hanem egy adatkorlátot: négy szezonban a páronkénti N→N+1 struktúra miatt a súlyozási séma nem különböztethető meg statisztikailag. A modell a következő wDRE-számítást alkalmazza:</p>
<p><span class="math display">\[
\text{wDRE} = \frac{\text{eff\_min}}{\text{eff\_min} + k_{\text{DRE}}} \cdot \frac{\sum_t \text{DRE}^{\text{shr}}_t \cdot \text{Min}_t \cdot \beta^{\Delta t}}{\sum_t \text{Min}_t \cdot \beta^{\Delta t}}
\qquad \beta = 0.5,\quad k_{\text{DRE}} = 400\ \text{perc}
\]</span></p>
<p>A <span class="math inline">\(k_{\text{DRE}}\)</span> paraméter egy <strong>második körös, DRE-szintű Bayesian shrinkage</strong>-et valósít meg. Motiváció: a stat-szintű shrinkage csökkenti az egyedi komponensek mintavételi zajját, de a DRE-formula maga NBA-adatokon kalibrált — az NB1-re vonatkozó maradék bizonytalanságot a DRE-szintű prior (0 = ligaátlag) felé húzás kezeli.</p>
<p><strong>Empirikus alap:</strong> ICC(DRE_raw) = 0.514 az NB1 adatokon → k_raw = 570 perc. Mivel a stat-szintű shrinkage már elvégzi az első körös zajcsökkentést, konzervatív <span class="math inline">\(k_{\text{DRE}} = 400\)</span> percet alkalmazunk.</p>
<p><strong>Hatás eff. percek szerint:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Eff. perc</th>
<th>Szorzó (<span class="math inline">\(\frac{\text{eff\_min}}{\text{eff\_min}+400}\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>128 (Gál Csongor)</td>
<td>0.24× — szinte teljesen 0-ra húzva</td>
</tr>
<tr class="even">
<td>400</td>
<td>0.50×</td>
</tr>
<tr class="odd">
<td>540 (Flasár Zalán)</td>
<td>0.57×</td>
</tr>
<tr class="even">
<td>800</td>
<td>0.67×</td>
</tr>
<tr class="odd">
<td>1400</td>
<td>0.78×</td>
</tr>
</tbody>
</table>
<p><strong>Minimális megjelenítési küszöb: 200 eff. perc</strong> (kb. fél szezon starters percek).</p>
<p>A <span class="math inline">\(\beta = 0.5\)</span>/szezon értéket <strong>elméleti alapon</strong> tartjuk meg (DARKO-hoz hasonló elvek, recency-bias). Pontosabb kalibráláshoz legalább 6–8 szezon szükséges.</p>
<p><strong>Alkalmazott súlyok (β=0.5):</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Szezon</th>
<th>Súly</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2025–26</td>
<td>1.000</td>
</tr>
<tr class="even">
<td>2024–25</td>
<td>0.500</td>
</tr>
<tr class="odd">
<td>2023–24</td>
<td>0.250</td>
</tr>
<tr class="even">
<td>2022–23</td>
<td>0.125</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="életkori-kiigazítás-aging-curve" class="level2">
<h2 class="anchored" data-anchor-id="életkori-kiigazítás-aging-curve">4. Életkori kiigazítás (Aging Curve)</h2>
<section id="módszer" class="level3">
<h3 class="anchored" data-anchor-id="módszer">4.1 Módszer</h3>
<p>Az NB1 2022–2026 adataiból, 200+ perces, egymást követő szezonokban szereplő játékosok esetén mértük a DRE évközi változását (ΔDRE/szezon) életkori csoportonként:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Empirikus aging curve — NB1 2022–2026</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Korcsoport</th>
<th style="text-align: center;">n (páros)</th>
<th style="text-align: center;">ΔDRE/szezon</th>
<th style="text-align: center;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">18–21</td>
<td style="text-align: center;">46</td>
<td style="text-align: center;">0.925</td>
<td style="text-align: center;">2.460</td>
</tr>
<tr class="even">
<td style="text-align: left;">22–24</td>
<td style="text-align: center;">46</td>
<td style="text-align: center;">0.330</td>
<td style="text-align: center;">3.035</td>
</tr>
<tr class="odd">
<td style="text-align: left;">25–27</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">0.275</td>
<td style="text-align: center;">3.029</td>
</tr>
<tr class="even">
<td style="text-align: left;">28–30</td>
<td style="text-align: center;">39</td>
<td style="text-align: center;">-0.389</td>
<td style="text-align: center;">3.070</td>
</tr>
<tr class="odd">
<td style="text-align: left;">31–33</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">-0.552</td>
<td style="text-align: center;">3.152</td>
</tr>
<tr class="even">
<td style="text-align: left;">34+</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">-0.331</td>
<td style="text-align: center;">2.036</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="értelmezés-és-korlátok" class="level3">
<h3 class="anchored" data-anchor-id="értelmezés-és-korlátok">4.2 Értelmezés és korlátok</h3>
<ul>
<li>A csúcs körülbelül <strong>25–27 éves kor körül</strong> van, ami közel esik az NBA 26.5 éves csúcsához</li>
<li>A 18–21 éveseknél a legélesebb az emelkedés (+0.925), de a mintaszám és a <strong>szelekcióbias</strong> jelentős: csak azok a fiatalok szerepelnek, akik 200+ percet kaptak, tehát már eleve tehetségesebben</li>
<li>A 34+ csoport kisebb mértékű hanyatlást mutat (–0.331 vs.&nbsp;–0.552 a 31–33-asoknál), ami szintén szelekciós hatás: az idős játékosok, akik még pályán vannak, kivételesen tartósak</li>
</ul>
</section>
<section id="alkalmazás-a-modellben" class="level3">
<h3 class="anchored" data-anchor-id="alkalmazás-a-modellben">4.3 Alkalmazás a modellben</h3>
<p>Az életkori kiigazítás a játékos <strong>várható következő éves fejlődését/hanyatlását</strong> adja hozzá a wDRE-hez, ±1.5/2.0 DRE pontos korláttal:</p>
<p><span class="math display">\[
\text{wDRE}^* = \text{wDRE} + \delta_{\text{kor}}
\]</span></p>
<hr>
</section>
</section>
<section id="a-teljes-wdre-pipeline" class="level2">
<h2 class="anchored" data-anchor-id="a-teljes-wdre-pipeline">5. A teljes wDRE* pipeline</h2>
<pre><code>Szezonos box-score adatok
        │
        ▼
STL/100 korrekció  →  DRE_raw (per szezon)
        │
        ▼
Bayesian shrinkage (stat-specifikus k, ligaátlag felé)
        │
        ▼
DRE_shrunk (per szezon)
        │
        ▼
Decay-súlyozott átlag (β=0.5, perc-súlyozással)
        │
        ▼
wDRE (karrierszintű, regresszált, recency-súlyozott)
        │
        ▼
Életkori kiigazítás (empirikus ΔDRE/szn, kor szerint)
        │
        ▼
wDRE* (végső, forward-looking metrika)</code></pre>
<p><strong>Referencia-tartomány (NB1, 300+ eff. perc):</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>wDRE*</th>
<th>Értelmezés</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&gt; +4</td>
<td>Ligaelite</td>
</tr>
<tr class="even">
<td>+2 – +4</td>
<td>Erős starter</td>
</tr>
<tr class="odd">
<td>0 – +2</td>
<td>Átlag starter</td>
</tr>
<tr class="even">
<td>−2 – 0</td>
<td>Rotációs játékos</td>
</tr>
<tr class="odd">
<td>&lt; −2</td>
<td>Fejlesztési fázis</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="korlátok-és-jövőbeli-fejlesztések" class="level2">
<h2 class="anchored" data-anchor-id="korlátok-és-jövőbeli-fejlesztések">6. Korlátok és jövőbeli fejlesztések</h2>
<section id="jelenlegi-korlátok" class="level3">
<h3 class="anchored" data-anchor-id="jelenlegi-korlátok">Jelenlegi korlátok</h3>
<p><strong>Adatkorlát — decay β:</strong> 4 szezon nem elegendő a β empirikus kalibrálásához. A cross-validáció minden β értéknél azonos R²-t ad. Megoldás: 6+ szezon adatával újrakalibrálni.</p>
<p><strong>DRE-formula NBA-ból:</strong> Az együtthatók (0.792, 1.680 stb.) NBA-szintű RAPM-regresszión alapulnak. Az NB1-re specifikus együtthatók becsléséhez RAPM vagy on-off adatokra lenne szükség mérkőzés szinten, egyéni játékosra lebontva — ez jelenleg nem áll rendelkezésre.</p>
<p><strong>Szelekciós bias az aging curve-ben:</strong> A 200+ perces szűrő a pályán lévő játékosokat emeli be, ami az extreme végeken (nagyon fiatalok, nagyon idősek) torzítja a görbe meredekségét.</p>
<p><strong>On-off adatok:</strong> A jelenlegi on_off_stats tábla szezonszintű összesítéseket tartalmaz, nem mérkőzésenkénti on-off adatokat. Utóbbiak lehetővé tennék a DRE-együtthatók NB1-specifikus újrabecslését.</p>
</section>
<section id="tervezett-fejlesztések" class="level3">
<h3 class="anchored" data-anchor-id="tervezett-fejlesztések">Tervezett fejlesztések</h3>
<ul>
<li><strong>β kalibrálás</strong> — több szezon hozzáadásával automatikusan optimalizálható</li>
<li><strong>Pozíció-specifikus shrinkage</strong> — centereknél más stabilitási profil, mint irányítóknál</li>
<li><strong>Csapatkontextus-korrekció</strong> — egy jó csapatban játszó play-maker magasabb AST%-ot mutat, mint egy rosszabb csapatban</li>
</ul>
<hr>
<p><em>Utolsó frissítés: 2025–26-os alapszakasz végi adatok alapján. Forrás: NB1 box-score adatbázis (bball_10_tables.db).</em></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">Levente Kaszai — Hungarian Sports Analytics</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>